<?php

/**
 * Escenarios de regresión internos del parser (NO son la hoja Casos_prueba del Excel Eulalio).
 * Derivados de pruebas FAMEDIC existentes y casos sintéticos de borde.
 *
 * @return list<array{
 *     case_id: string,
 *     study_id: string,
 *     study_name: string,
 *     indications: string,
 *     expected_categories: list<string>,
 *     expected_requirement_types: list<string>,
 *     preserved_substrings: list<string>,
 *     allow_unrecognized: bool
 * }>
 */
return [
    [
        'case_id' => 'REG-01',
        'study_id' => '1001',
        'study_name' => 'Química sanguínea',
        'indications' => 'Ayuno de 8 horas.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['fasting_exact_hours'],
        'preserved_substrings' => ['Ayuno de 8 horas'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-02',
        'study_id' => '1002',
        'study_name' => 'Perfil lipídico',
        'indications' => 'Ayuno de 12 horas.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['fasting_exact_hours'],
        'preserved_substrings' => ['12 horas'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-03',
        'study_id' => '1003',
        'study_name' => 'Tetra Marcador',
        'indications' => "- Presentarse con ayuno de 8 -14 horas.\n- Se deberá realizar entre las semanas 14 a 22 de gestación por ultrasonido.\n- Copia de interpretación estudio de ultrasonido realizado dentro de las semanas permitidas.",
        'expected_categories' => ['fasting', 'age_condition', 'documentation'],
        'expected_requirement_types' => ['fasting_range_hours', 'gestational_weeks_window', 'interpretation_copy'],
        'preserved_substrings' => ['8 -14', 'semanas 14 a 22', 'Copia de interpretación'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-04',
        'study_id' => '1004',
        'study_name' => 'Urocultivo',
        'indications' => 'Desechar el primer chorro y recolectar el chorro medio.',
        'expected_categories' => ['urine_simple', 'urine_simple'],
        'expected_requirement_types' => ['discard_first_stream', 'mid_stream_urine'],
        'preserved_substrings' => ['primer chorro', 'chorro medio'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-05',
        'study_id' => '1005',
        'study_name' => 'Examen general de orina',
        'indications' => 'Desechar el primer chorro y recolectar el chorro medio.',
        'expected_categories' => ['urine_simple', 'urine_simple'],
        'expected_requirement_types' => ['discard_first_stream', 'mid_stream_urine'],
        'preserved_substrings' => ['Desechar el primer chorro'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-06',
        'study_id' => '1006',
        'study_name' => 'Creatinina en orina',
        'indications' => 'Recolectar después de 4 horas de la última micción.',
        'expected_categories' => ['urine_simple'],
        'expected_requirement_types' => ['urine_after_void_hours'],
        'preserved_substrings' => ['4 horas', 'última micción'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-07',
        'study_id' => '1007',
        'study_name' => 'Urocultivo',
        'indications' => 'Recolectar primera orina de la mañana.',
        'expected_categories' => ['urine_simple'],
        'expected_requirement_types' => ['first_morning_urine'],
        'preserved_substrings' => ['primera orina de la mañana'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-08',
        'study_id' => '1008',
        'study_name' => 'EGO',
        'indications' => 'Ayuno de 8 - 14 horas. Llenar por lo menos las tres cuartas partes del recipiente.',
        'expected_categories' => ['fasting', 'urine_simple'],
        'expected_requirement_types' => ['fasting_range_hours', 'urine_fill_level'],
        'preserved_substrings' => ['8 - 14 horas', 'tres cuartas partes'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-09',
        'study_id' => '1009',
        'study_name' => 'Orina 24 horas',
        'indications' => 'Recolectar orina de 24 horas en frasco con preservador.',
        'expected_categories' => ['urine_24h', 'container_preservative'],
        'expected_requirement_types' => ['urine_24h_collection', 'preservative'],
        'preserved_substrings' => ['orina de 24 horas', 'preservador'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-10',
        'study_id' => '1010',
        'study_name' => 'Coprocultivo',
        'indications' => 'Recolectar muestra de heces en recipiente estéril.',
        'expected_categories' => ['stool', 'container_preservative'],
        'expected_requirement_types' => ['stool_sample', 'sterile_container'],
        'preserved_substrings' => ['heces', 'estéril'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-11',
        'study_id' => '1011',
        'study_name' => 'Espermograma',
        'indications' => 'Abstinencia sexual de 3 a 5 días. Entregar muestra seminal en laboratorio.',
        'expected_categories' => ['gynecological', 'semen'],
        'expected_requirement_types' => ['sexual_abstinence_days', 'semen_sample'],
        'preserved_substrings' => ['Abstinencia sexual', 'muestra seminal'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-12',
        'study_id' => '1012',
        'study_name' => 'Citología vaginal',
        'indications' => 'No tener relaciones sexuales 24 horas antes. No estar en periodo de menstruación.',
        'expected_categories' => ['gynecological', 'gynecological'],
        'expected_requirement_types' => ['no_intercourse', 'no_menstruation'],
        'preserved_substrings' => ['24 horas', 'menstruación'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-13',
        'study_id' => '1013',
        'study_name' => 'Perfil hepático',
        'indications' => 'Evitar alcohol 24 horas antes del estudio.',
        'expected_categories' => ['diet_substance_exercise'],
        'expected_requirement_types' => ['avoid_alcohol'],
        'preserved_substrings' => ['Evitar alcohol 24 horas'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-14',
        'study_id' => '1014',
        'study_name' => 'CK total',
        'indications' => 'Evitar ejercicio intenso 24 horas antes.',
        'expected_categories' => ['diet_substance_exercise'],
        'expected_requirement_types' => ['avoid_exercise'],
        'preserved_substrings' => ['ejercicio intenso'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-15',
        'study_id' => '1015',
        'study_name' => 'Glucosa',
        'indications' => 'No requiere ayuno.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['no_fasting'],
        'preserved_substrings' => ['No requiere ayuno'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-16',
        'study_id' => '1016',
        'study_name' => 'Biometría',
        'indications' => 'Sin preparación especial.',
        'expected_categories' => ['no_preparation'],
        'expected_requirement_types' => ['no_preparation'],
        'preserved_substrings' => ['Sin preparación'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-17',
        'study_id' => '1017',
        'study_name' => 'Ultrasonido pélvico',
        'indications' => 'Presentarse con vejiga llena. Beber 1 litro de agua 1 hora antes.',
        'expected_categories' => ['hydration', 'hydration'],
        'expected_requirement_types' => ['full_bladder', 'drink_water_volume'],
        'preserved_substrings' => ['vejiga llena', '1 litro de agua'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-18',
        'study_id' => '1018',
        'study_name' => 'RMN cerebral',
        'indications' => 'Informar si tiene marcapasos o implantes metálicos.',
        'expected_categories' => ['metal_implant', 'metal_implant'],
        'expected_requirement_types' => ['pacemaker', 'implant'],
        'preserved_substrings' => ['marcapasos', 'implantes metálicos'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-19',
        'study_id' => '1019',
        'study_name' => 'TAC con contraste',
        'indications' => 'Traer creatinina reciente antes del estudio con contraste.',
        'expected_categories' => ['creatinine_contrast', 'creatinine_contrast'],
        'expected_requirement_types' => ['creatinine_required', 'contrast_study'],
        'preserved_substrings' => ['creatinina', 'contraste'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-20',
        'study_id' => '1020',
        'study_name' => 'RMN de pie',
        'indications' => '-Realizar previa cita.',
        'expected_categories' => ['appointment'],
        'expected_requirement_types' => ['prior_appointment'],
        'preserved_substrings' => ['previa cita'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-21',
        'study_id' => '1021',
        'study_name' => 'Estudio pediátrico',
        'indications' => 'Menores de 12 años deben acudir con acompañante e identificación oficial.',
        'expected_categories' => ['age_condition', 'companion_identification', 'companion_identification'],
        'expected_requirement_types' => ['age_years_max', 'companion_required', 'identification_required'],
        'preserved_substrings' => ['Menores de 12 años', 'acompañante', 'identificación'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-22',
        'study_id' => '1022',
        'study_name' => 'Tirosina',
        'indications' => 'Suspender medicamento por 72 horas antes del estudio.',
        'expected_categories' => ['medication'],
        'expected_requirement_types' => ['suspend_medication_duration'],
        'preserved_substrings' => ['Suspender medicamento', '72 horas'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-23',
        'study_id' => '1023',
        'study_name' => 'Perfil lipídico',
        'indications' => 'Presentarse hidratado.',
        'expected_categories' => ['hydration'],
        'expected_requirement_types' => ['hydrated'],
        'preserved_substrings' => ['Presentarse hidratado'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-24',
        'study_id' => '1024',
        'study_name' => 'Urocultivo',
        'indications' => 'Desechar el primer chorro. Recolectar chorro medio. Entregar en menos de 2 horas.',
        'expected_categories' => ['urine_simple', 'urine_simple', 'urine_simple'],
        'expected_requirement_types' => ['discard_first_stream', 'mid_stream_urine', 'urine_delivery_time'],
        'preserved_substrings' => ['menos de 2 horas'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-25',
        'study_id' => '1025',
        'study_name' => 'Estudio A',
        'indications' => 'Ayuno de 6 a 8 horas.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['fasting_range_hours'],
        'preserved_substrings' => ['6 a 8 horas'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-26',
        'study_id' => '1026',
        'study_name' => 'Estudio B',
        'indications' => 'Ayuno de 10 a 12 horas.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['fasting_range_hours'],
        'preserved_substrings' => ['10 a 12 horas'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-27',
        'study_id' => '1027',
        'study_name' => 'Paquete',
        'indications' => '',
        'expected_categories' => [],
        'expected_requirement_types' => [],
        'preserved_substrings' => [],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-28',
        'study_id' => '1028',
        'study_name' => 'Estudio incompleto',
        'indications' => 'Ayuno de horas.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['fasting_incomplete'],
        'preserved_substrings' => ['Ayuno de horas'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-29',
        'study_id' => '1029',
        'study_name' => 'Estudio ambiguo',
        'indications' => 'Tomar 2 chilitos antes del estudio.',
        'expected_categories' => ['unknown'],
        'expected_requirement_types' => ['unknown_unit'],
        'preserved_substrings' => ['chilitos'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-30',
        'study_id' => '1030',
        'study_name' => 'Receta',
        'indications' => 'Presentar receta médica y orden médica vigente.',
        'expected_categories' => ['documentation'],
        'expected_requirement_types' => ['medical_order'],
        'preserved_substrings' => ['receta médica', 'orden médica'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-31',
        'study_id' => '1031',
        'study_name' => 'Neonato',
        'indications' => 'Recién nacido: tomar muestra capilar según indicación del médico.',
        'expected_categories' => ['age_condition'],
        'expected_requirement_types' => ['newborn'],
        'preserved_substrings' => ['Recién nacido'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-32',
        'study_id' => '1032',
        'study_name' => 'Perfil tiroideo',
        'indications' => 'Evitar alimentos grasos 24 horas antes.',
        'expected_categories' => ['diet_substance_exercise', 'sample_timing'],
        'expected_requirement_types' => ['avoid_fatty_foods', 'hours_before_study'],
        'preserved_substrings' => ['alimentos grasos', '24 horas antes'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-33',
        'study_id' => '1033',
        'study_name' => 'Cafeína',
        'indications' => 'No tomar cafeína 12 horas antes.',
        'expected_categories' => ['diet_substance_exercise'],
        'expected_requirement_types' => ['avoid_caffeine'],
        'preserved_substrings' => ['cafeína'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-34',
        'study_id' => '1034',
        'study_name' => 'Ayuno mínimo',
        'indications' => 'Presentarse con ayuno de al menos 8 horas.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['fasting_minimum_hours'],
        'preserved_substrings' => ['al menos 8 horas'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-35',
        'study_id' => '1035',
        'study_name' => 'Lípidos',
        'indications' => 'Presentarse con ayuno.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['fasting_present'],
        'preserved_substrings' => ['Presentarse con ayuno'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-36',
        'study_id' => '1036',
        'study_name' => 'Cultivo',
        'indications' => 'Llevar recipiente estéril.',
        'expected_categories' => ['container_preservative'],
        'expected_requirement_types' => ['sterile_container'],
        'preserved_substrings' => ['recipiente estéril'],
        'allow_unrecognized' => false,
    ],
    [
        'case_id' => 'REG-37',
        'study_id' => '1037',
        'study_name' => 'Multilínea',
        'indications' => "Ayuno de 8 horas.\nEvitar alcohol 24 horas antes.\nLlevar identificación.",
        'expected_categories' => ['fasting', 'diet_substance_exercise', 'companion_identification'],
        'expected_requirement_types' => ['fasting_exact_hours', 'avoid_alcohol', 'identification_required'],
        'preserved_substrings' => ['Ayuno de 8 horas', 'Evitar alcohol', 'identificación'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-38',
        'study_id' => '1038',
        'study_name' => 'Parcial',
        'indications' => 'Recolectar orina y seguir protocolo interno XYZ-999 no documentado.',
        'expected_categories' => ['urine_simple', 'unknown'],
        'expected_requirement_types' => ['collect_urine', 'unrecognized_fragment'],
        'preserved_substrings' => ['protocolo interno XYZ-999'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-39',
        'study_id' => '1039',
        'study_name' => 'Negación',
        'indications' => 'No ayuno requerido para este estudio.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['no_fasting'],
        'preserved_substrings' => ['No ayuno'],
        'allow_unrecognized' => true,
    ],
    [
        'case_id' => 'REG-40',
        'study_id' => '1040',
        'study_name' => 'Compra múltiple',
        'indications' => 'Ayuno de 8 horas.',
        'expected_categories' => ['fasting'],
        'expected_requirement_types' => ['fasting_exact_hours'],
        'preserved_substrings' => ['Ayuno de 8 horas'],
        'allow_unrecognized' => false,
    ],
];
