<?php

/**
 * Variables del .env sin fila en `settings`: se listan todas; si existe entrada aquí,
 * se compara con config() como en metadatos. Amplía env_to_config cuando agregues ENV nuevas.
 */
return [

    'sensitive_patterns' => [
        '/PASSWORD/i',
        '/SECRET/i',
        '/PRIVATE/i',
        '/_KEY$/i',
        '/_TOKEN$/i',
        '/API_KEY$/i',
        '/TOTP/i',
        '/WEBHOOK/i',
    ],

    'env_to_config' => [
        'APP_NAME' => 'app.name',
        'APP_ENV' => 'app.env',
        'APP_DEBUG' => 'app.debug',
        'APP_URL' => 'app.url',
        'APP_TIMEZONE' => 'app.timezone',
        'APP_LOCALE' => 'app.locale',
        'APP_FALLBACK_LOCALE' => 'app.fallback_locale',
        'APP_FAKER_LOCALE' => 'app.faker_locale',
        'APP_KEY' => 'app.key',
        'APP_MAINTENANCE_DRIVER' => 'app.maintenance.driver',
        'APP_MAINTENANCE_STORE' => 'app.maintenance.store',
        'DB_CONNECTION' => 'database.default',
        'DB_HOST' => 'database.connections.mysql.host',
        'DB_PORT' => 'database.connections.mysql.port',
        'DB_DATABASE' => 'database.connections.mysql.database',
        'DB_USERNAME' => 'database.connections.mysql.username',
        'DB_PASSWORD' => 'database.connections.mysql.password',
        'MAIL_MAILER' => 'mail.default',
        'MAIL_HOST' => 'mail.mailers.smtp.host',
        'MAIL_PORT' => 'mail.mailers.smtp.port',
        'MAIL_USERNAME' => 'mail.mailers.smtp.username',
        'MAIL_PASSWORD' => 'mail.mailers.smtp.password',
        'MAIL_ENCRYPTION' => 'mail.mailers.smtp.encryption',
        'MAIL_FROM_ADDRESS' => 'mail.from.address',
        'MAIL_FROM_NAME' => 'mail.from.name',
        'MAILGUN_DOMAIN' => 'services.mailgun.domain',
        'MAILGUN_SECRET' => 'services.mailgun.secret',
        'MAILGUN_ENDPOINT' => 'services.mailgun.endpoint',
        'FILESYSTEM_DISK' => 'filesystems.default',
        'AWS_ACCESS_KEY_ID' => 'filesystems.disks.s3.key',
        'AWS_SECRET_ACCESS_KEY' => 'filesystems.disks.s3.secret',
        'AWS_DEFAULT_REGION' => 'filesystems.disks.s3.region',
        'AWS_BUCKET' => 'filesystems.disks.s3.bucket',
        'AWS_URL' => 'filesystems.disks.s3.url',
        'AWS_ENDPOINT' => 'filesystems.disks.s3.endpoint',
        'AWS_USE_PATH_STYLE_ENDPOINT' => 'filesystems.disks.s3.use_path_style_endpoint',
        'SESSION_DRIVER' => 'session.driver',
        'SESSION_LIFETIME' => 'session.lifetime',
        'SESSION_ENCRYPT' => 'session.encrypt',
        'SESSION_PATH' => 'session.path',
        'SESSION_DOMAIN' => 'session.domain',
        'CACHE_STORE' => 'cache.default',
        'CACHE_PREFIX' => 'cache.prefix',
        'QUEUE_CONNECTION' => 'queue.default',
        'LOG_CHANNEL' => 'logging.default',
        'LOG_LEVEL' => 'logging.channels.single.level',
        'SCOUT_DRIVER' => 'scout.driver',
        'SCOUT_QUEUE' => 'scout.queue',
        'ALGOLIA_APP_ID' => 'scout.algolia.id',
        'ALGOLIA_SECRET' => 'scout.algolia.secret',
        'GOOGLE_CLIENT_ID' => 'services.google.client_id',
        'GOOGLE_CLIENT_SECRET' => 'services.google.client_secret',
        'GOOGLE_REDIRECT_URI' => 'services.google.redirect',
        'FB_PIXEL_ID' => 'services.facebook.pixel_id',
        'FB_CAPI_TOKEN' => 'services.facebook.capi_token',
        'FB_TEST_EVENT_CODE' => 'services.facebook.test_event_code',
        'FB_BATCH_SIZE_LIMIT' => 'services.facebook.batch_size_limit',
        'STRIPE_KEY' => 'services.stripe.key',
        'STRIPE_SECRET' => 'services.stripe.secret',
        'PAYPAL_MODE' => 'services.paypal.mode',
        'PAYPAL_CLIENT_ID' => 'services.paypal.client_id',
        'PAYPAL_SECRET' => 'services.paypal.secret',
        'PAYPAL_WEBHOOK_ID' => 'services.paypal.webhook_id',
        'VITAU_URL' => 'services.vitau.url',
        'VITAU_API_KEY' => 'services.vitau.key',
        'VITAU_EMAIL' => 'services.vitau.email',
        'VITAU_PASSWORD' => 'services.vitau.password',
        'VITAU_PAYMENT_METHOD' => 'services.vitau.payment_method',
        'MURGUIA_URL' => 'services.murguia.url',
        'MURGUIA_USERNAME' => 'services.murguia.username',
        'MURGUIA_PASSWORD' => 'services.murguia.password',
        'MURGUIA_QUEUE_NAME' => 'services.murguia.queue',
        'MURGUIA_INSTITUTIONAL_ALLOW_NON_ODESSA' => 'famedic.murguia_institutional_allow_non_odessa_morph',
        'GDA_URL' => 'services.gda.url',
        'GDA_REPORT_EMAILS' => 'services.gda.report_emails',
        'GDA_CONCIERGE_EMAILS' => 'services.gda.concierge_emails',
        'GDA_SWISSLAB_ID' => 'services.gda.brands.swisslab.brand_id',
        'GDA_SWISSLAB_AGREEMENT_ID' => 'services.gda.brands.swisslab.brand_agreement_id',
        'GDA_SWISSLAB_TOKEN' => 'services.gda.brands.swisslab.token',
        'GDA_OLAB_ID' => 'services.gda.brands.olab.brand_id',
        'GDA_OLAB_AGREEMENT_ID' => 'services.gda.brands.olab.brand_agreement_id',
        'GDA_OLAB_TOKEN' => 'services.gda.brands.olab.token',
        'GDA_AZTECA_ID' => 'services.gda.brands.azteca.brand_id',
        'GDA_AZTECA_AGREEMENT_ID' => 'services.gda.brands.azteca.brand_agreement_id',
        'GDA_AZTECA_TOKEN' => 'services.gda.brands.azteca.token',
        'GDA_JENNER_ID' => 'services.gda.brands.jenner.brand_id',
        'GDA_JENNER_AGREEMENT_ID' => 'services.gda.brands.jenner.brand_agreement_id',
        'GDA_JENNER_TOKEN' => 'services.gda.brands.jenner.token',
        'GDA_LIACSA_ID' => 'services.gda.brands.liacsa.brand_id',
        'GDA_LIACSA_AGREEMENT_ID' => 'services.gda.brands.liacsa.brand_agreement_id',
        'GDA_LIACSA_TOKEN' => 'services.gda.brands.liacsa.token',
        'GDA_BRANDS_FAMEDIC_BRAND_ID' => 'services.gda.brands.famedic.brand_id',
        'GDA_BRANDS_FAMEDIC_TOKEN' => 'services.gda.brands.famedic.token',
        'GDA_BRANDS_FAMEDIC_BRAND_AGREEMENT_ID' => 'services.gda.brands.famedic.brand_agreement_id',
        'ODESSA_URL' => 'services.odessa.url',
        'ODESSA_REFUND_REPORT_EMAILS' => 'services.odessa.refund_report_emails',
        'RECAPTCHA_SITE_KEY' => 'services.recaptcha.site_key',
        'RECAPTCHA_SECRET_KEY' => 'services.recaptcha.secret_key',
        'ACTIVE_CAMPAIGN_API_ENDPOINT' => 'services.activecampaign.endpoint',
        'ACTIVE_CAMPAIGN_API_TOKEN' => 'services.activecampaign.token',
        'ACTIVE_CAMPAIGN_ACCOUNT_ID' => 'services.activecampaign.account_id',
        'ACTIVE_CAMPAIGN_EVENT_KEY' => 'services.activecampaign.event_key',
        'ACTIVE_CAMPAIGN_LIST_NEW_USERS' => 'services.activecampaign.list_new_users',
        'ACTIVE_CAMPAIGN_TAG_REGISTRO_WEB' => 'services.activecampaign.tag_registro_web',
        'ACTIVE_CAMPAIGN_CART_ABANDONED_MINUTES' => 'services.activecampaign.cart_abandoned_minutes',
        'ACTIVECAMPAIGN_TAG_ABANDONED_CARTS_ENABLED' => 'services.activecampaign.tag_abandoned_carts_enabled',
        'ACTIVE_CAMPAIGN_TAG_PHARMACY_PURCHASE_COMPLETED' => 'services.activecampaign.tag_pharmacy_purchase_completed',
        'ACTIVE_CAMPAIGN_TAG_LABORATORY_PURCHASE_COMPLETED' => 'services.activecampaign.tag_laboratory_purchase_completed',
        'ACTIVE_CAMPAIGN_TAG_LAB_SAMPLE_COLLECTED' => 'services.activecampaign.tag_lab_sample_collected',
        'ACTIVE_CAMPAIGN_TAG_LAB_RESULTS_AVAILABLE' => 'services.activecampaign.tag_lab_results_available',
        'ACTIVE_CAMPAIGN_TAG_REGISTRO_NUEVO' => 'services.activecampaign.tag_registro_nuevo',
        'EFEVOO_ENVIRONMENT' => 'efevoo.environment',
        'EFEVOO_API_URL' => 'efevoo.api_url',
        'EFEVOO_API_USER' => 'efevoo.api_user',
        'EFEVOO_API_KEY' => 'efevoo.api_key',
        'EFEVOO_TOTP_SECRET' => 'efevoo.totp_secret',
        'EFEVOO_CLAVE' => 'efevoo.clave',
        'EFEVOO_CLIENTE' => 'efevoo.cliente',
        'EFEVOO_VECTOR' => 'efevoo.vector',
        'EFEVOO_VERIFY_SSL' => 'efevoo.verify_ssl',
        'EFEVOO_LOG_REQUESTS' => 'efevoo.log_requests',
        'EFEVOOPAY_FIXED_TOKEN' => 'efevoo.fixed_token',
        'EFEVOOPAY_FORCE_SIMULATION' => 'efevoo.force_simulation',
        'AUTH_AUTO_VERIFY_PHONE_AFTER_EMAIL' => 'auth.auto_verify_phone_after_email',
        'LABORATORY_PURCHASE_PDFS_PATH' => 'famedic.storage_paths.laboratory_purchase_pdfs',
        'INSTITUTIONAL_ODESSA_SUBSCRIPTION_YEARS' => 'famedic.institutional_odessa_subscription_years',
        'INSTITUTIONAL_ODESSA_SUBSCRIPTION_PRICE_CENTS' => 'famedic.institutional_odessa_subscription_price_cents',
        'REDIS_HOST' => 'database.redis.default.host',
        'REDIS_PASSWORD' => 'database.redis.default.password',
        'REDIS_PORT' => 'database.redis.default.port',
        'REDIS_CLIENT' => 'database.redis.client',
        'BROADCAST_CONNECTION' => 'broadcasting.default',
        'VITE_RECAPTCHA_SITE_KEY' => 'recaptcha.api_site_key',
        'VITE_RECAPTCHA_SECRET_KEY' => 'recaptcha.api_secret_key',
    ],

];
