<?php

namespace App\Imports;
use Carbon\Carbon;
class UsersMedicalAttentionTree
{
    public static function data(): array
    {
        $now = Carbon::now();
        $password = bcrypt('Pa$$word');
        return [            
            [
                'id' => 300,
                'name' => 'Banda Aguilar',
                'paternal_lastname' => 'Sergio',
                'maternal_lastname' => 'Angello',
                'full_name' => 'BANDA AGUILAR SERGIO ANGELLO',
                'email' => 'sergio.banda@hydrocontwm.com',
                'birth_date' => '1996-09-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 301,
                'name' => 'Macias Chavez',
                'paternal_lastname' => 'Claudia',
                'maternal_lastname' => 'Alejandra',
                'full_name' => 'MACIAS CHAVEZ CLAUDIA ALEJANDRA',
                'email' => 'claudia.macias@hydrocontwm.com',
                'birth_date' => '1965-09-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 302,
                'name' => 'Miguel Angel',
                'paternal_lastname' => 'Ruiz',
                'maternal_lastname' => 'Perez',
                'full_name' => 'RUIZ PEREZ MIGUEL ANGEL',
                'email' => 'miguel.ruiz@hydrocontwm.com',
                'birth_date' => '1988-11-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 303,
                'name' => 'Gonzalez Juan Carlos',
                'paternal_lastname' => 'De La',
                'maternal_lastname' => 'Cruz',
                'full_name' => 'DE LA CRUZ GONZALEZ JUAN CARLOS',
                'email' => 'juan.delacruz@hydrocontwm.com',
                'birth_date' => '1999-01-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 304,
                'name' => 'Adrian',
                'paternal_lastname' => 'Reyes',
                'maternal_lastname' => 'Cruz',
                'full_name' => 'REYES CRUZ ADRIAN',
                'email' => 'adrian.reyes@hydrocontwm.com',
                'birth_date' => '1997-11-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 305,
                'name' => 'Lemus',
                'paternal_lastname' => 'Vega',
                'maternal_lastname' => 'Uriel',
                'full_name' => 'LEMUS VEGA URIEL',
                'email' => 'uriel.lemus@hydrocontwm.com',
                'birth_date' => '1987-01-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 306,
                'name' => 'Adrian',
                'paternal_lastname' => 'Flores',
                'maternal_lastname' => 'Vazquez',
                'full_name' => 'FLORES VAZQUEZ ADRIAN',
                'email' => 'adrian.flores@hydrocontwm.com',
                'birth_date' => '1977-02-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 307,
                'name' => 'Ramirez Garcia',
                'paternal_lastname' => 'Carlos',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'RAMIREZ GARCIA CARLOS ALBERTO',
                'email' => 'carlos.ramirez@hydrocontwm.com',
                'birth_date' => '1997-08-22',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 308,
                'name' => 'Nexticapan Reynosa',
                'paternal_lastname' => 'Leslie',
                'maternal_lastname' => 'Yazmin',
                'full_name' => 'NEXTICAPAN REYNOSA LESLIE YAZMIN',
                'email' => 'leslie.nexticapan@hydrocontwm.com',
                'birth_date' => '1985-05-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 309,
                'name' => 'Nieto Medina',
                'paternal_lastname' => 'Emilio',
                'maternal_lastname' => 'Ezequiel',
                'full_name' => 'NIETO MEDINA EMILIO EZEQUIEL',
                'email' => 'emilio.nieto@hydrocontwm.com',
                'birth_date' => '1993-07-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 310,
                'name' => 'Miguel De Jesus',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'Galvan',
                'full_name' => 'GARCIA GALVAN MIGUEL DE JESUS',
                'email' => 'miguel.garcia@hydrocontwm.com',
                'birth_date' => '2001-09-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 311,
                'name' => 'Mario Eduardo',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Perez',
                'full_name' => 'HERNANDEZ PEREZ MARIO EDUARDO',
                'email' => 'mario.hernandez@hydrocontwm.com',
                'birth_date' => '1985-04-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 312,
                'name' => 'Morales',
                'paternal_lastname' => 'Molina',
                'maternal_lastname' => 'Alexander',
                'full_name' => 'MORALES MOLINA ALEXANDER',
                'email' => 'alexander.morales@hydrocontwm.com',
                'birth_date' => '1987-08-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 313,
                'name' => 'Jose Angel',
                'paternal_lastname' => 'Peña',
                'maternal_lastname' => 'Ventura',
                'full_name' => 'PEÑA VENTURA JOSE ANGEL',
                'email' => 'jose.ventura@hydrocontwm.com',
                'birth_date' => '1979-03-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 314,
                'name' => 'Padilla Rodriguez',
                'paternal_lastname' => 'Monica',
                'maternal_lastname' => 'Lizbeth',
                'full_name' => 'PADILLA RODRIGUEZ MONICA LIZBETH',
                'email' => 'monica.padilla@hydrocontwm.com',
                'birth_date' => '1969-12-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 315,
                'name' => 'Gerardo',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'Juarez',
                'full_name' => 'PEREZ JUAREZ GERARDO',
                'email' => 'gerardo.perez@hydrocontwm.com',
                'birth_date' => '1977-04-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 316,
                'name' => 'Ramirez Alvarez',
                'paternal_lastname' => 'Jocelyne',
                'maternal_lastname' => 'Michel',
                'full_name' => 'RAMIREZ ALVAREZ JOCELYNE MICHEL',
                'email' => 'jocelyne.ramirez@hydrocontwm.com',
                'birth_date' => '1968-02-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 317,
                'name' => 'Prado Granados',
                'paternal_lastname' => 'Diana',
                'maternal_lastname' => 'Jazmin',
                'full_name' => 'PRADO GRANADOS DIANA JAZMIN',
                'email' => 'diana.prado@hydrocontwm.com',
                'birth_date' => '1996-12-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 318,
                'name' => 'Quiñonez Audeves',
                'paternal_lastname' => 'Maria',
                'maternal_lastname' => 'Elizabeth',
                'full_name' => 'QUIÑONEZ AUDEVES MARIA ELIZABETH',
                'email' => 'maria.quinonez@hydrocontwm.com',
                'birth_date' => '1993-11-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 319,
                'name' => 'Acosta Saldivar',
                'paternal_lastname' => 'Carlos',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'ACOSTA SALDIVAR CARLOS ALBERTO',
                'email' => 'carlos.acosta@hydrocontwm.com',
                'birth_date' => '1979-08-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 320,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Zenaida',
                'full_name' => 'HERNANDEZ HERNANDEZ ZENAIDA',
                'email' => 'zenaida.hernandez@hydrocontwm.com',
                'birth_date' => '1998-10-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 321,
                'name' => 'Villela Maldonado',
                'paternal_lastname' => 'Ruben',
                'maternal_lastname' => 'Adolfo',
                'full_name' => 'VILLELA MALDONADO RUBEN ADOLFO',
                'email' => 'ruben.villela@hydrocontwm.com',
                'birth_date' => '1981-04-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 322,
                'name' => 'Juan Pablo',
                'paternal_lastname' => 'Bustos',
                'maternal_lastname' => 'Ortiz',
                'full_name' => 'BUSTOS ORTIZ JUAN PABLO',
                'email' => 'juan.bustos@hydrocontwm.com',
                'birth_date' => '1989-05-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 323,
                'name' => 'Ramos Salazar',
                'paternal_lastname' => 'Diana',
                'maternal_lastname' => 'Laura',
                'full_name' => 'RAMOS SALAZAR DIANA LAURA',
                'email' => 'diana.ramos@hydrocontwm.com',
                'birth_date' => '1986-04-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 324,
                'name' => 'Jose',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'GONZALEZ MARTINEZ JOSE',
                'email' => 'jose.gonzalez@hydrocontwm.com',
                'birth_date' => '2000-01-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 325,
                'name' => 'Porras',
                'paternal_lastname' => 'Mercado',
                'maternal_lastname' => 'Moises',
                'full_name' => 'PORRAS MERCADO MOISES',
                'email' => 'moises.porras@hydrocontwm.com',
                'birth_date' => '1992-06-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 326,
                'name' => 'Hernandez Benitez',
                'paternal_lastname' => 'Anthony',
                'maternal_lastname' => 'Abisai',
                'full_name' => 'HERNANDEZ BENITEZ ANTHONY ABISAI',
                'email' => 'anthony.hernande@hydrocontwm.com',
                'birth_date' => '1964-04-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 327,
                'name' => 'Luis Angel',
                'paternal_lastname' => 'Salas',
                'maternal_lastname' => 'Perez',
                'full_name' => 'SALAS PEREZ LUIS ANGEL',
                'email' => 'luis.salas@hydrocontwm.com',
                'birth_date' => '1976-08-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 328,
                'name' => 'Noriega Vidrio',
                'paternal_lastname' => 'Lidian',
                'maternal_lastname' => 'Sinahi',
                'full_name' => 'NORIEGA VIDRIO LIDIAN SINAHI',
                'email' => 'lidian.noriega@hydrocontwm.com',
                'birth_date' => '1999-01-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 329,
                'name' => 'Olvera Perez',
                'paternal_lastname' => 'Roberto',
                'maternal_lastname' => 'Abraham',
                'full_name' => 'OLVERA PEREZ ROBERTO ABRAHAM',
                'email' => 'roberto.olvera@hydrocontwm.com',
                'birth_date' => '1971-12-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 330,
                'name' => 'Carmona Reyes',
                'paternal_lastname' => 'Ana',
                'maternal_lastname' => 'Guadalupe',
                'full_name' => 'CARMONA REYES ANA GUADALUPE',
                'email' => 'ana.carmona@hydrocontwm.com',
                'birth_date' => '1985-07-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 331,
                'name' => 'Gerardo',
                'paternal_lastname' => 'Reyes',
                'maternal_lastname' => 'Bravo',
                'full_name' => 'REYES BRAVO GERARDO',
                'email' => 'gerardo.reyes@hydrocontwm.com',
                'birth_date' => '1980-05-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 332,
                'name' => 'Gonzalez',
                'paternal_lastname' => 'Moreno',
                'maternal_lastname' => 'Citlaly',
                'full_name' => 'GONZALEZ MORENO CITLALY',
                'email' => 'citlaly.gonzalez@hydrocontwm.com',
                'birth_date' => '1992-04-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 333,
                'name' => 'Hernandez Hernandez',
                'paternal_lastname' => 'Maria',
                'maternal_lastname' => 'De Los Angeles',
                'full_name' => 'HERNANDEZ HERNANDEZ MARIA DE LOS ANGELES',
                'email' => 'maria.hernandez@hydrocontwm.com',
                'birth_date' => '1973-04-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 334,
                'name' => 'Cruz Martinez',
                'paternal_lastname' => 'Santos',
                'maternal_lastname' => 'Blas',
                'full_name' => 'CRUZ MARTINEZ SANTOS BLAS',
                'email' => 'santos.cruz@hydrocontwm.com',
                'birth_date' => '1977-05-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 335,
                'name' => 'Jose Miguel',
                'paternal_lastname' => 'Delgado',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'DELGADO MARTINEZ JOSE MIGUEL',
                'email' => 'jose.delgado@hydrocontwm.com',
                'birth_date' => '1982-03-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 336,
                'name' => 'Alfonso De Jesus',
                'paternal_lastname' => 'Carrillo',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'CARRILLO GARCIA ALFONSO DE JESUS',
                'email' => 'alfonso.carrillo@hydrocontwm.com',
                'birth_date' => '1982-07-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 337,
                'name' => 'Tovar Lopez',
                'paternal_lastname' => 'Carlos',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'TOVAR LOPEZ CARLOS ALBERTO',
                'email' => 'carlos.tovar@hydrocontwm.com',
                'birth_date' => '1992-04-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 338,
                'name' => 'Gallegos',
                'paternal_lastname' => 'Medina',
                'maternal_lastname' => 'Edgar',
                'full_name' => 'GALLEGOS MEDINA EDGAR',
                'email' => 'edgar.gallegos@hydrocontwm.com',
                'birth_date' => '1972-06-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 339,
                'name' => 'Terron Hernandez',
                'paternal_lastname' => 'Maria',
                'maternal_lastname' => 'Teresa',
                'full_name' => 'TERRON HERNANDEZ MARIA TERESA',
                'email' => 'maria.terron@hydrocontwm.com',
                'birth_date' => '1993-03-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 340,
                'name' => 'Manuel De Jesus',
                'paternal_lastname' => 'Longoria',
                'maternal_lastname' => 'Jalomo',
                'full_name' => 'LONGORIA JALOMO MANUEL DE JESUS',
                'email' => 'manuel.longoria@hydrocontwm.com',
                'birth_date' => '1973-03-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 341,
                'name' => 'Jesus Rodolfo Alejandro',
                'paternal_lastname' => 'Vazquez',
                'maternal_lastname' => 'Ramirez',
                'full_name' => 'VAZQUEZ RAMIREZ JESUS RODOLFO ALEJANDRO',
                'email' => 'rodolfo.vazquez@hydrocontwm.com',
                'birth_date' => '1985-12-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 342,
                'name' => 'Luis Alfredo',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Vallejo',
                'full_name' => 'GONZALEZ VALLEJO LUIS ALFREDO',
                'email' => 'alfredo.gonzalez@hydrocontwm.com',
                'birth_date' => '1994-10-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 343,
                'name' => 'Ramirez Romero',
                'paternal_lastname' => 'Laura',
                'maternal_lastname' => 'Aracely',
                'full_name' => 'RAMIREZ ROMERO LAURA ARACELY',
                'email' => 'laura.ramirez@hydrocontwm.com',
                'birth_date' => '2002-11-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 344,
                'name' => 'Levi Eduardo',
                'paternal_lastname' => 'Villarreal',
                'maternal_lastname' => 'Argueta',
                'full_name' => 'VILLARREAL ARGUETA LEVI EDUARDO',
                'email' => 'levi.villarreal@hydrocontwm.com',
                'birth_date' => '1989-03-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 345,
                'name' => 'Benitez Patiño',
                'paternal_lastname' => 'Raul',
                'maternal_lastname' => 'Abdon',
                'full_name' => 'BENITEZ PATIÑO RAUL ABDON',
                'email' => 'raul.benitez@hydrocontwm.com',
                'birth_date' => '1983-05-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 346,
                'name' => 'Alejandro',
                'paternal_lastname' => 'Diego',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'DIEGO HERNANDEZ ALEJANDRO',
                'email' => 'alejandro.diego@hydrocontwm.com',
                'birth_date' => '1990-11-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 347,
                'name' => 'Vargas Pacheco',
                'paternal_lastname' => 'Monica',
                'maternal_lastname' => 'Aileen',
                'full_name' => 'VARGAS PACHECO MONICA AILEEN',
                'email' => 'monica.vargas@hydrocontwm.com',
                'birth_date' => '1995-03-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 348,
                'name' => 'Hector Daniel',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Hidalgo',
                'full_name' => 'HERNANDEZ HIDALGO HECTOR DANIEL',
                'email' => 'hector.hernandez@hydrocontwm.com',
                'birth_date' => '1999-09-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 349,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'Lucio',
                'full_name' => 'HERNANDEZ GARCIA LUCIO',
                'email' => 'lucio.hernandez@hydrocontwm.com',
                'birth_date' => '2003-10-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 350,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Guzman',
                'maternal_lastname' => 'Othon',
                'full_name' => 'HERNANDEZ GUZMAN OTHON',
                'email' => 'othon.hernandez@hydrocontwm.com',
                'birth_date' => '1997-11-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 351,
                'name' => 'Juan Manuel',
                'paternal_lastname' => 'Zuñiga',
                'maternal_lastname' => 'Vasquez',
                'full_name' => 'ZUÑIGA VASQUEZ JUAN MANUEL',
                'email' => 'iga@hydrocontwm.com',
                'birth_date' => '1989-11-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 352,
                'name' => 'Gonzalez Mondragon',
                'paternal_lastname' => 'Pablo',
                'maternal_lastname' => 'David',
                'full_name' => 'GONZALEZ MONDRAGON PABLO DAVID',
                'email' => 'pablo.gonzalez@hydrocontwm.com',
                'birth_date' => '1995-01-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 353,
                'name' => 'Salas',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Jaime',
                'full_name' => 'SALAS HERNANDEZ JAIME',
                'email' => 'jaime.salas@hydrocontwm.com',
                'birth_date' => '1996-10-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 354,
                'name' => 'Rafael',
                'paternal_lastname' => 'Romero',
                'maternal_lastname' => 'Ortiz',
                'full_name' => 'ROMERO ORTIZ RAFAEL',
                'email' => 'rafael.romero@hydrocontwm.com',
                'birth_date' => '1985-05-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 355,
                'name' => 'Oscar',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'Pineda',
                'full_name' => 'PEREZ PINEDA OSCAR',
                'email' => 'oscar.pineda@hydrocontwm.com',
                'birth_date' => '1998-11-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 356,
                'name' => 'Elizalde',
                'paternal_lastname' => 'Najera',
                'maternal_lastname' => 'Noelia',
                'full_name' => 'ELIZALDE NAJERA NOELIA',
                'email' => 'noelia.elizalde@hydrocontwm.com',
                'birth_date' => '1983-02-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 357,
                'name' => 'Gonzalez Martinez',
                'paternal_lastname' => 'Marian',
                'maternal_lastname' => 'Estefania',
                'full_name' => 'GONZALEZ MARTINEZ MARIAN ESTEFANIA',
                'email' => 'marian.gonzalez@hydrocontwm.com',
                'birth_date' => '1980-11-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 358,
                'name' => 'Eduardo',
                'paternal_lastname' => 'Marquez',
                'maternal_lastname' => 'Barron',
                'full_name' => 'MARQUEZ BARRON EDUARDO',
                'email' => 'eduardo.marquez@hydrocontwm.com',
                'birth_date' => '1989-03-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 359,
                'name' => 'Perez Uitz',
                'paternal_lastname' => 'Magdiel',
                'maternal_lastname' => 'Abisai',
                'full_name' => 'PEREZ UITZ MAGDIEL ABISAI',
                'email' => 'magdiel.perez@hydrocontwm.com',
                'birth_date' => '1985-08-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 360,
                'name' => 'Juan Carlos',
                'paternal_lastname' => 'Becerra',
                'maternal_lastname' => 'Arteaga',
                'full_name' => 'BECERRA ARTEAGA JUAN CARLOS',
                'email' => 'juan.becerra@hydrocontwm.com',
                'birth_date' => '2000-01-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 361,
                'name' => 'Flores',
                'paternal_lastname' => 'Mar',
                'maternal_lastname' => 'Levit',
                'full_name' => 'FLORES MAR LEVIT',
                'email' => 'levit.flores@hydrocontwm.com',
                'birth_date' => '1995-10-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 362,
                'name' => 'Segura',
                'paternal_lastname' => 'Diaz',
                'maternal_lastname' => 'Mario',
                'full_name' => 'SEGURA DIAZ MARIO',
                'email' => 'mario.segura@hydrocontwm.com',
                'birth_date' => '1991-09-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 363,
                'name' => 'Maria Jose',
                'paternal_lastname' => 'Renteria',
                'maternal_lastname' => 'Flores',
                'full_name' => 'RENTERIA FLORES MARIA JOSE',
                'email' => 'maria.renteria@hydrocon.com.mx',
                'birth_date' => '1979-07-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 364,
                'name' => 'Juan Carlos',
                'paternal_lastname' => 'Sanchez',
                'maternal_lastname' => 'Sifuentes',
                'full_name' => 'SANCHEZ SIFUENTES JUAN CARLOS',
                'email' => 'juan.sanchez@hydrocontwm.com',
                'birth_date' => '1998-10-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 365,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Rubio',
                'maternal_lastname' => 'Santiago',
                'full_name' => 'HERNANDEZ RUBIO SANTIAGO',
                'email' => 'santiago.hernandez@hydrocontwm.com',
                'birth_date' => '1994-11-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 366,
                'name' => 'Vazquez',
                'paternal_lastname' => 'Bautista',
                'maternal_lastname' => 'Cinthya',
                'full_name' => 'VAZQUEZ BAUTISTA CINTHYA',
                'email' => 'cinthya.vazquez@hydrocontwm.com',
                'birth_date' => '1987-08-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 367,
                'name' => 'Ramirez Sanchez',
                'paternal_lastname' => 'Marco',
                'maternal_lastname' => 'Vinicio',
                'full_name' => 'RAMIREZ SANCHEZ MARCO VINICIO',
                'email' => 'vinicio.ramirez@hydrocontwm.com',
                'birth_date' => '1991-06-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 368,
                'name' => 'Garcia Arriaga',
                'paternal_lastname' => 'Ramses',
                'maternal_lastname' => 'Usiel',
                'full_name' => 'GARCIA ARRIAGA RAMSES USIEL',
                'email' => 'ramses.garcia@hydrocontwm.com',
                'birth_date' => '2002-04-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 369,
                'name' => 'Kevin Leonardo',
                'paternal_lastname' => 'Martinez',
                'maternal_lastname' => 'Gonzalez',
                'full_name' => 'MARTINEZ GONZALEZ KEVIN LEONARDO',
                'email' => 'kevin.martinez@hydrocontwm.com',
                'birth_date' => '1978-02-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 370,
                'name' => 'Vazquez Morales',
                'paternal_lastname' => 'Jesus',
                'maternal_lastname' => 'Gustavo',
                'full_name' => 'VAZQUEZ MORALES JESUS GUSTAVO',
                'email' => 'jesus.vazquez@hydrocontwm.com',
                'birth_date' => '1992-12-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 371,
                'name' => 'Bautista Sanchez',
                'paternal_lastname' => 'Luz',
                'maternal_lastname' => 'Rosario',
                'full_name' => 'BAUTISTA SANCHEZ LUZ ROSARIO',
                'email' => 'luz.bautista@hydrocon.com.mx',
                'birth_date' => '2002-12-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 372,
                'name' => 'Eduardo',
                'paternal_lastname' => 'Ramirez',
                'maternal_lastname' => 'Serna',
                'full_name' => 'RAMIREZ SERNA EDUARDO',
                'email' => 'eduardo.ramirez@hydrocontwm.com',
                'birth_date' => '1996-11-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 373,
                'name' => 'Julio Cesar',
                'paternal_lastname' => 'Salazar',
                'maternal_lastname' => 'Salazar',
                'full_name' => 'SALAZAR SALAZAR JULIO CESAR',
                'email' => 'salazarjulioc33@gmail.com',
                'birth_date' => '1971-07-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 374,
                'name' => 'Juan Carlos',
                'paternal_lastname' => 'Estrada',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'ESTRADA HERNANDEZ JUAN CARLOS',
                'email' => 'aldoyahir4@gmail.com',
                'birth_date' => '1968-07-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 375,
                'name' => 'Garcia',
                'paternal_lastname' => 'Ruvalcaba',
                'maternal_lastname' => 'Narciso',
                'full_name' => 'GARCIA RUVALCABA NARCISO',
                'email' => 'cyanchicho@gmail.com',
                'birth_date' => '1971-10-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 376,
                'name' => 'Garcia',
                'paternal_lastname' => 'Tovar',
                'maternal_lastname' => 'Bernardo',
                'full_name' => 'GARCIA TOVAR BERNARDO',
                'email' => 'garciatovarbernardo@gmail.com',
                'birth_date' => '1976-05-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 377,
                'name' => 'Adrian',
                'paternal_lastname' => 'Moreno',
                'maternal_lastname' => 'Segura',
                'full_name' => 'MORENO SEGURA ADRIAN',
                'email' => 'adrian35.cyanlabs.xk@gmail.com',
                'birth_date' => '1978-09-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 378,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Naranjo',
                'maternal_lastname' => 'Enrique',
                'full_name' => 'HERNANDEZ NARANJO ENRIQUE',
                'email' => 'nenrique125@gmail.com',
                'birth_date' => '1984-11-22',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 379,
                'name' => 'Ricardo',
                'paternal_lastname' => 'Moreno',
                'maternal_lastname' => 'Jaramillo',
                'full_name' => 'MORENO JARAMILLO RICARDO',
                'email' => 'rikamoreno84@gmail.com',
                'birth_date' => '1984-05-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 380,
                'name' => 'Sergio Luis',
                'paternal_lastname' => 'Torres',
                'maternal_lastname' => 'Bernal',
                'full_name' => 'TORRES BERNAL SERGIO LUIS',
                'email' => 'sergio58g@gmail.com',
                'birth_date' => '1968-10-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 381,
                'name' => 'Moreno',
                'paternal_lastname' => 'Alvarado',
                'maternal_lastname' => 'Mario',
                'full_name' => 'MORENO ALVARADO MARIO',
                'email' => 'mario.moreno84@outlook.com',
                'birth_date' => '1973-11-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 382,
                'name' => 'Jesus',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'HERNANDEZ HERNANDEZ JESUS',
                'email' => 'jesushdz21051988@gmail.com',
                'birth_date' => '1988-05-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 383,
                'name' => 'Serrato Luna',
                'paternal_lastname' => 'Carlos',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'SERRATO LUNA CARLOS ALBERTO',
                'email' => 'carlosserrato1672@gmail.com',
                'birth_date' => '1993-03-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 384,
                'name' => 'Garcia',
                'paternal_lastname' => 'Ramos',
                'maternal_lastname' => 'Joel',
                'full_name' => 'GARCIA RAMOS JOEL',
                'email' => 'joelgarcia1175@gmail.com',
                'birth_date' => '1975-11-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 385,
                'name' => 'Mojica',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Yair',
                'full_name' => 'MOJICA HERNANDEZ YAIR',
                'email' => 'mojicayair5@gmail.com',
                'birth_date' => '1984-05-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 386,
                'name' => 'Martinez',
                'paternal_lastname' => 'Victoriano',
                'maternal_lastname' => 'Joel',
                'full_name' => 'MARTINEZ VICTORIANO JOEL',
                'email' => 'mtz.victoriano@gmail.com',
                'birth_date' => '1976-04-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 387,
                'name' => 'Julio Cesar',
                'paternal_lastname' => 'Silva',
                'maternal_lastname' => 'Rivera',
                'full_name' => 'SILVA RIVERA JULIO CESAR',
                'email' => 'cesar_sil@live.com.mx',
                'birth_date' => '1973-03-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 388,
                'name' => 'Elias',
                'paternal_lastname' => 'Garza',
                'maternal_lastname' => 'Ramirez',
                'full_name' => 'GARZA RAMIREZ ELIAS',
                'email' => 'eliasramirez2527@gmail.com',
                'birth_date' => '1973-10-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 389,
                'name' => 'Jose Alberto',
                'paternal_lastname' => 'Armendariz',
                'maternal_lastname' => 'Barajas',
                'full_name' => 'ARMENDARIZ BARAJAS JOSE ALBERTO',
                'email' => 'armendarizbarajasalberto@gmail.com',
                'birth_date' => '1983-08-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 390,
                'name' => 'Garcia',
                'paternal_lastname' => 'Tovar',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'GARCIA TOVAR ALBERTO',
                'email' => 'garciatovaralberto095@gmail.com',
                'birth_date' => '1976-09-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 391,
                'name' => 'Martinez Gonzalez',
                'paternal_lastname' => 'Roberto',
                'maternal_lastname' => 'Edivaldo',
                'full_name' => 'MARTINEZ GONZALEZ ROBERTO EDIVALDO',
                'email' => 'eddy.chikis1992@gmail.com',
                'birth_date' => '1991-11-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 392,
                'name' => 'Sanchez Rangel',
                'paternal_lastname' => 'Bertha',
                'maternal_lastname' => 'Alicia',
                'full_name' => 'SANCHEZ RANGEL BERTHA ALICIA',
                'email' => 'alicia0724b@gmail.com',
                'birth_date' => '1978-07-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 393,
                'name' => 'Jose Alfredo',
                'paternal_lastname' => 'Dominguez',
                'maternal_lastname' => 'Coronado',
                'full_name' => 'DOMINGUEZ CORONADO JOSE ALFREDO',
                'email' => 'fredydom73@gmail.com',
                'birth_date' => '1983-08-31',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 394,
                'name' => 'Chavez Espinosa',
                'paternal_lastname' => 'Victor',
                'maternal_lastname' => 'Alfonso',
                'full_name' => 'CHAVEZ ESPINOSA VICTOR ALFONSO',
                'email' => 'dianalanderos0614@gmail.com',
                'birth_date' => '1987-01-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 395,
                'name' => 'Valdez Velazquez',
                'paternal_lastname' => 'Edgar',
                'maternal_lastname' => 'Eliel',
                'full_name' => 'VALDEZ VELAZQUEZ EDGAR ELIEL',
                'email' => 'edgareliel98@gmail.com',
                'birth_date' => '1992-04-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 396,
                'name' => 'Hector',
                'paternal_lastname' => 'Ramirez',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'RAMIREZ HERNANDEZ HECTOR',
                'email' => 'hr7830185@gmail.com',
                'birth_date' => '1995-06-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 397,
                'name' => 'Narvaez Berumen',
                'paternal_lastname' => 'Laura',
                'maternal_lastname' => 'Antonia',
                'full_name' => 'NARVAEZ BERUMEN LAURA ANTONIA',
                'email' => 'lauranarvaez182@gmail.com',
                'birth_date' => '1983-08-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 398,
                'name' => 'Guajardo Armendariz',
                'paternal_lastname' => 'Amalia',
                'maternal_lastname' => 'Isabel',
                'full_name' => 'GUAJARDO ARMENDARIZ AMALIA ISABEL',
                'email' => 'amalia.guajardo@outlook.com',
                'birth_date' => '1978-02-22',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 399,
                'name' => 'Sanchez Robles',
                'paternal_lastname' => 'Jorge',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'SANCHEZ ROBLES JORGE ALBERTO',
                'email' => 'jorgealbertosanchezrobles04@gmail.com',
                'birth_date' => '1980-04-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];
    }
}
