<?php

namespace App\Imports;
use Carbon\Carbon;
class UsersMedicalAttentionTwo
{
    public static function data(): array
    {
        $now = Carbon::now();
        $password = bcrypt('Pa$$word');
        return [
            [
                'id' => 101,
                'name' => 'Noe',
                'paternal_lastname' => 'Jeronimo',
                'maternal_lastname' => 'Gallegos',
                'full_name' => 'JERONIMO GALLEGOS',
                'email' => 'noe.sanchez@key.com.mx',
                'birth_date' => '1966-09-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 102,
                'name' => 'Gilberto Mario',
                'paternal_lastname' => 'Garza',
                'maternal_lastname' => 'Gongora',
                'full_name' => 'GILBERTO MARIO GARZA GONGORA',
                'email' => 'gilberto.garza@keyquimica.com',
                'birth_date' => '1984-03-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 103,
                'name' => 'Carlos Enrique',
                'paternal_lastname' => 'Betancourt',
                'maternal_lastname' => 'Dominguez',
                'full_name' => 'CARLOS ENRIQUE BETANCOURT DOMINGUEZ',
                'email' => 'carlos.betancourt@keyquimica.com',
                'birth_date' => '1992-12-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 104,
                'name' => 'Osimar',
                'paternal_lastname' => 'Rosales',
                'maternal_lastname' => 'Solis',
                'full_name' => 'OSIMAR ROSALES SOLIS',
                'email' => 'osimar.gonzalez@keyquimica.com',
                'birth_date' => '1996-11-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 105,
                'name' => 'Omar Aram',
                'paternal_lastname' => 'Ponce',
                'maternal_lastname' => 'Bretado',
                'full_name' => 'OMAR ARAM PONCE BRETADO',
                'email' => 'omar.ponce@keyquimica.com',
                'birth_date' => '1983-09-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 106,
                'name' => 'Jose Luis',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Cornejo',
                'full_name' => 'JOSE LUIS HERNANDEZ CORNEJO',
                'email' => 'hernandezconejojoselui4@gmail.com',
                'birth_date' => '1969-02-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 107,
                'name' => 'Armando Arcangel',
                'paternal_lastname' => 'Sanchez',
                'maternal_lastname' => 'Brito',
                'full_name' => 'ARMANDO ARCANGEL SANCHEZ BRITO',
                'email' => 'armando.sanchez@keyquimica.com',
                'birth_date' => '1976-11-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 108,
                'name' => 'Candy Victoria',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Rodriguez',
                'full_name' => 'CANDY VICTORIA HERNANDEZ RODRIGUEZ',
                'email' => 'dulcehdzrdzz@gmail.com',
                'birth_date' => '1995-11-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 109,
                'name' => 'Eduardo Jair',
                'paternal_lastname' => 'Villegas',
                'maternal_lastname' => 'Vega',
                'full_name' => 'EDUARDO JAIR VILLEGAS VEGA',
                'email' => 'eduardo.villegas@keyquimica.com',
                'birth_date' => '1999-05-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 110,
                'name' => 'Alondra Guadalupe',
                'paternal_lastname' => 'Valencia',
                'maternal_lastname' => 'Ulloa',
                'full_name' => 'ALONDRA GUADALUPE VALENCIA ULLOA',
                'email' => 'av26062001@gmail.com',
                'birth_date' => '2001-06-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 111,
                'name' => 'Gilberto Saul',
                'paternal_lastname' => 'Blasco',
                'maternal_lastname' => 'Manzo',
                'full_name' => 'GILBERTO SAUL BLASCO MANZO',
                'email' => 'gilberto.blasco@key.com.mx',
                'birth_date' => '1977-06-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 112,
                'name' => 'Cenobio Guadalupe',
                'paternal_lastname' => 'De Jesus',
                'maternal_lastname' => 'Cruz',
                'full_name' => 'CENOBIO GUADALUPE DE JESUS CRUZ',
                'email' => 'cenobio.dejesus@keyquimica.com',
                'birth_date' => '1982-06-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 113,
                'name' => 'Juan Enrique',
                'paternal_lastname' => 'Espinosa',
                'maternal_lastname' => 'Rivera',
                'full_name' => 'JUAN ENRIQUE ESPINOSA RIVERA',
                'email' => 'juan.espinosa@keyquimica.com',
                'birth_date' => '1984-08-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 114,
                'name' => 'Juan Pablo',
                'paternal_lastname' => 'Flores',
                'maternal_lastname' => 'Olvera',
                'full_name' => 'JUAN PABLO FLORES OLVERA',
                'email' => 'juan.flores@keyquimica.com',
                'birth_date' => '1979-01-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 115,
                'name' => 'Omar David',
                'paternal_lastname' => 'Sanchez',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'OMAR DAVID SANCHEZ MARTINEZ',
                'email' => 'omar.sanchez@keyquimica.com',
                'birth_date' => '1987-06-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 116,
                'name' => 'Jose Manuel',
                'paternal_lastname' => 'Cab',
                'maternal_lastname' => 'Perez',
                'full_name' => 'JOSE MANUEL CAB PEREZ',
                'email' => 'jose.cab@keyquimica.com',
                'birth_date' => '1990-05-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 117,
                'name' => 'Hector Abraham',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'Cejudo',
                'full_name' => 'HECTOR ABRAHAM GARCIA CEJUDO',
                'email' => 'hector.garcia@keyquimica.com',
                'birth_date' => '1998-06-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 118,
                'name' => 'Marvin Adrian',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'Mendoza',
                'full_name' => 'MARVIN ADRIAN GARCIA MENDOZA',
                'email' => 'marvin.garcia@keyquimica.com',
                'birth_date' => '1997-07-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 119,
                'name' => 'Jaime',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Cliofas',
                'full_name' => 'JAIME HERNANDEZ CLIOFAS',
                'email' => 'jaime.hernandez@keyquimica.com',
                'birth_date' => '1990-05-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 120,
                'name' => 'Gustavo',
                'paternal_lastname' => 'Juarez',
                'maternal_lastname' => 'Leal',
                'full_name' => 'GUSTAVO JUAREZ LEAL',
                'email' => 'gustavo.juarez@keyquimica.com',
                'birth_date' => '1997-10-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 121,
                'name' => 'Brayan Eduardo',
                'paternal_lastname' => 'Lopez',
                'maternal_lastname' => 'Mosqueda',
                'full_name' => 'BRAYAN EDUARDO LOPEZ MOSQUEDA',
                'email' => 'brayan.lopez@keyquimica.com',
                'birth_date' => '1997-01-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 122,
                'name' => 'Oscar',
                'paternal_lastname' => 'Madrigal',
                'maternal_lastname' => 'Reza',
                'full_name' => 'OSCAR MADRIGAL REZA',
                'email' => 'oscar.madrigal@keyquimica.com',
                'birth_date' => '1984-11-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 123,
                'name' => 'Gerardo',
                'paternal_lastname' => 'Mejia',
                'maternal_lastname' => 'Morales',
                'full_name' => 'GERARDO MEJIA MORALES',
                'email' => 'gerardo.mejia@keyquimica.com',
                'birth_date' => '1985-03-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 124,
                'name' => 'Maribel',
                'paternal_lastname' => 'Mendieta',
                'maternal_lastname' => 'Garduño',
                'full_name' => 'MARIBEL MENDIETA GARDUÑO',
                'email' => 'maribel.mendieta@keyquimica.com',
                'birth_date' => '1977-03-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 125,
                'name' => 'Juan Teodulo',
                'paternal_lastname' => 'Ojeda',
                'maternal_lastname' => 'Monterrosas',
                'full_name' => 'JUAN TEODULO OJEDA MONTERROSAS',
                'email' => 'juan.ojeda@key.com.mx',
                'birth_date' => '1966-06-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 126,
                'name' => 'Adrian',
                'paternal_lastname' => 'Ortiz',
                'maternal_lastname' => 'Orozco',
                'full_name' => 'ADRIAN ORTIZ OROZCO',
                'email' => 'adrian.ortiz@keyquimica.com',
                'birth_date' => '1980-07-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 127,
                'name' => 'Daniel Martin',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'DANIEL MARTIN PEREZ GARCIA',
                'email' => 'daniel.perezg@keyquimica.com',
                'birth_date' => '1989-04-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 128,
                'name' => 'Rogelio',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'Gervacio',
                'full_name' => 'ROGELIO PEREZ GERVACIO',
                'email' => 'rogelio.perez@key.com.mx',
                'birth_date' => '1991-10-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 129,
                'name' => 'Govani',
                'paternal_lastname' => 'Quintanar',
                'maternal_lastname' => 'Escobedo',
                'full_name' => 'GOVANI QUINTANAR ESCOBEDO',
                'email' => 'govani.quintanar@keyquimica.com',
                'birth_date' => '1989-10-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 130,
                'name' => 'Cristina Elizabeth',
                'paternal_lastname' => 'Quiroz',
                'maternal_lastname' => 'Ortega',
                'full_name' => 'CRISTINA ELIZABETH QUIROZ ORTEGA',
                'email' => 'cristina.quiroz@keyquimica.com',
                'birth_date' => '1987-03-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 131,
                'name' => 'Luis Adrian',
                'paternal_lastname' => 'Rodriguez',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'LUIS ADRIAN RODRIGUEZ GARCIA',
                'email' => 'adrian.rodriguez@keyquimica.com',
                'birth_date' => '1992-07-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 132,
                'name' => 'Juan Antonio',
                'paternal_lastname' => 'Roldan',
                'maternal_lastname' => 'Torres',
                'full_name' => 'JUAN ANTONIO ROLDAN TORRES',
                'email' => 'juan.roldan@keyquimica.com',
                'birth_date' => '1986-02-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 133,
                'name' => 'Jose Luis',
                'paternal_lastname' => 'Romero',
                'maternal_lastname' => 'Castillo',
                'full_name' => 'JOSE LUIS ROMERO CASTILLO',
                'email' => 'jose.romero@keyquimica.com',
                'birth_date' => '1982-08-22',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 134,
                'name' => 'Miguel Angel',
                'paternal_lastname' => 'Saucedo',
                'maternal_lastname' => 'Barranco',
                'full_name' => 'MIGUEL ANGEL SAUCEDO BARRANCO',
                'email' => 'miguel.saucedo@keyquimica.com',
                'birth_date' => '1994-01-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 135,
                'name' => 'Victor Hugo',
                'paternal_lastname' => 'Segundo',
                'maternal_lastname' => 'Marquez',
                'full_name' => 'VICTOR HUGO SEGUNDO MARQUEZ',
                'email' => 'victor.segundo@keyquimica.com',
                'birth_date' => '1999-03-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 136,
                'name' => 'Irvin Orelt',
                'paternal_lastname' => 'Vargas',
                'maternal_lastname' => 'Cardenas',
                'full_name' => 'IRVIN ORELT VARGAS CARDENAS',
                'email' => 'irvin.vargas@keyquimica.com',
                'birth_date' => '2005-05-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 137,
                'name' => 'Alejandro Javier',
                'paternal_lastname' => 'Villegas',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'ALEJANDRO JAVIER VILLEGAS HERNANDEZ',
                'email' => 'alejandro.villegas@keyquimica.com',
                'birth_date' => '1994-04-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 138,
                'name' => 'Guillermo',
                'paternal_lastname' => 'Arzate',
                'maternal_lastname' => 'De La Cruz',
                'full_name' => 'GUILLERMO ARZATE DE LA CRUZ',
                'email' => 'guillermo.arzate@keyquimica.com',
                'birth_date' => '1996-03-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 139,
                'name' => 'Lidia Aide',
                'paternal_lastname' => 'Rubio',
                'maternal_lastname' => 'Cardenas',
                'full_name' => 'LIDIA AIDE RUBIO CARDENAS',
                'email' => 'recepcion.facturas@key.com.mx',
                'birth_date' => '1999-07-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 140,
                'name' => 'Joel Alberto',
                'paternal_lastname' => 'Bastida',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'JOEL ALBERTO BASTIDA MARTINEZ',
                'email' => 'joel.bastida@keyquimica.com',
                'birth_date' => '1997-04-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 141,
                'name' => 'Angel De Jesus',
                'paternal_lastname' => 'Barrientos',
                'maternal_lastname' => 'Arias',
                'full_name' => 'ANGEL DE JESUS BARRIENTOS ARIAS',
                'email' => 'angel.barrientos@keyquimica.com',
                'birth_date' => '1996-03-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 142,
                'name' => 'Daniel',
                'paternal_lastname' => 'Vergara',
                'maternal_lastname' => 'Lopez',
                'full_name' => 'DANIEL VERGARA LOPEZ',
                'email' => 'daniel.vergara@keyquimica.com',
                'birth_date' => '1981-02-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 143,
                'name' => 'Jorge Abraham',
                'paternal_lastname' => 'Jimenez',
                'maternal_lastname' => 'Gomez',
                'full_name' => 'JORGE ABRAHAM JIMENEZ GOMEZ',
                'email' => 'jorge.jimenez@keyquimica.com',
                'birth_date' => '1998-07-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 144,
                'name' => 'Brenda Jazmin',
                'paternal_lastname' => 'Esparza',
                'maternal_lastname' => 'Cavazos',
                'full_name' => 'BRENDA JAZMIN ESPARZA CAVAZOS',
                'email' => 'esparzabrenda914@gmail.com',
                'birth_date' => '1987-03-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 145,
                'name' => 'Miguel Angel',
                'paternal_lastname' => 'Guzman',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'MIGUEL ANGEL GUZMAN MARTINEZ',
                'email' => 'miguelangel10102132@gmail.com',
                'birth_date' => '2005-08-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 146,
                'name' => 'Victor Manuel',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Castillo',
                'full_name' => 'VICTOR MANUEL GONZALEZ CASTILLO',
                'email' => 'victor.gonzalez@key.com.mx',
                'birth_date' => '1962-08-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 147,
                'name' => 'Hector',
                'paternal_lastname' => 'Berlanga',
                'maternal_lastname' => 'Espinoza',
                'full_name' => 'HECTOR BERLANGA ESPINOZA',
                'email' => 'hector.berlanga@key.com.mx',
                'birth_date' => '1963-12-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 148,
                'name' => 'Ricardo Luis',
                'paternal_lastname' => 'Cerda',
                'maternal_lastname' => 'Vela',
                'full_name' => 'RICARDO LUIS CERDA VELA',
                'email' => 'ricardo.cerda@key.com.mx',
                'birth_date' => '1980-07-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 149,
                'name' => 'Osvaldo Christian',
                'paternal_lastname' => 'Elizondo',
                'maternal_lastname' => 'Rodriguez',
                'full_name' => 'OSVALDO CHRISTIAN ELIZONDO RODRIGUEZ',
                'email' => 'osvaldo.elizondo@key.com.mx',
                'birth_date' => '1980-04-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 150,
                'name' => 'Guadalupe',
                'paternal_lastname' => 'Neri',
                'maternal_lastname' => 'Cardona',
                'full_name' => 'GUADALUPE NERI CARDONA',
                'email' => 'guadalupe.neri@key.com.mx',
                'birth_date' => '1988-08-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 151,
                'name' => 'Osvaldo',
                'paternal_lastname' => 'Martinez',
                'maternal_lastname' => 'Llamas',
                'full_name' => 'OSVALDO MARTINEZ LLAMAS',
                'email' => 'osvaldo.martinez@key.com.mx',
                'birth_date' => '1964-06-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 152,
                'name' => 'Francisco Javier',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Ovalle',
                'full_name' => 'FRANCISCO JAVIER GONZALEZ OVALLE',
                'email' => 'francisco.gonzalez@key.com.mx',
                'birth_date' => '1981-01-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 153,
                'name' => 'Oscar',
                'paternal_lastname' => 'Herrera',
                'maternal_lastname' => 'Camarillo',
                'full_name' => 'OSCAR HERRERA CAMARILLO',
                'email' => 'oscar.herrera@key.com.mx',
                'birth_date' => '1968-11-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 154,
                'name' => 'Carlos Tadeo',
                'paternal_lastname' => 'Marquez',
                'maternal_lastname' => 'Reyes',
                'full_name' => 'CARLOS TADEO MARQUEZ REYES',
                'email' => 'carlos.marquez@key.com.mx',
                'birth_date' => '1981-08-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 155,
                'name' => 'Eliuth',
                'paternal_lastname' => 'Soto',
                'maternal_lastname' => 'Treviño',
                'full_name' => 'ELIUTH SOTO TREVIÑO',
                'email' => 'eliuth.soto@key.com.mx',
                'birth_date' => '1968-04-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 156,
                'name' => 'Orlando',
                'paternal_lastname' => 'Treviño',
                'maternal_lastname' => 'Flores',
                'full_name' => 'ORLANDO TREVIÑO FLORES',
                'email' => 'orlando.trevino@key.com.mx',
                'birth_date' => '1986-11-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 157,
                'name' => 'Oscar Ramiro',
                'paternal_lastname' => 'Diosdado',
                'maternal_lastname' => 'Lopez',
                'full_name' => 'OSCAR RAMIRO DIOSDADO LOPEZ',
                'email' => 'oscar.diosdado@key.com.mx',
                'birth_date' => '1981-03-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 158,
                'name' => 'Jose Alejandro',
                'paternal_lastname' => 'Resendiz',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'JOSE ALEJANDRO RESENDIZ HERNANDEZ',
                'email' => 'jose.resendiz@key.com.mx',
                'birth_date' => '1975-12-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 159,
                'name' => 'Andres',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'Escobedo',
                'full_name' => 'ANDRES PEREZ ESCOBEDO',
                'email' => 'andres.perez@key.com.mx',
                'birth_date' => '1973-08-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 160,
                'name' => 'Pablo Josefak',
                'paternal_lastname' => 'Mendoza',
                'maternal_lastname' => 'Diosdado',
                'full_name' => 'PABLO JOSEFAK MENDOZA DIOSDADO',
                'email' => 'pm822156@gmail.com',
                'birth_date' => '2004-11-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 161,
                'name' => 'Julio Cesar',
                'paternal_lastname' => 'Vallejo',
                'maternal_lastname' => 'Rosales',
                'full_name' => 'JULIO CESAR VALLEJO ROSALES',
                'email' => 'julio.vallejo@key.com.mx',
                'birth_date' => '1995-05-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 162,
                'name' => 'Elias',
                'paternal_lastname' => 'Rodriguez',
                'maternal_lastname' => 'Treviño',
                'full_name' => 'ELIAS RODRIGUEZ TREVIÑO',
                'email' => 'elias.rodriguez@key.com.mx',
                'birth_date' => '1981-02-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 163,
                'name' => 'Rodolfo',
                'paternal_lastname' => 'Gaona',
                'maternal_lastname' => 'Blanco',
                'full_name' => 'RODOLFO GAONA BLANCO',
                'email' => 'rodolgo.gaona@key.com.mx',
                'birth_date' => '1974-12-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 164,
                'name' => 'Jose Luis',
                'paternal_lastname' => 'Aleman',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'JOSE LUIS ALEMAN MARTINEZ',
                'email' => 'jose.aleman@keyquimica.com',
                'birth_date' => '1968-08-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 165,
                'name' => 'Julio Geronimo',
                'paternal_lastname' => 'Palacios',
                'maternal_lastname' => 'Camacho',
                'full_name' => 'JULIO GERONIMO PALACIOS CAMACHO',
                'email' => 'julio.palacios@keyquimica.com',
                'birth_date' => '1992-05-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 166,
                'name' => 'Javier Orlando',
                'paternal_lastname' => 'Quezada',
                'maternal_lastname' => 'Longoria',
                'full_name' => 'JAVIER ORLANDO QUEZADA LONGORIA',
                'email' => 'javier.quezada@keyquimica.com',
                'birth_date' => '1998-12-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 167,
                'name' => 'Rafael Antonio',
                'paternal_lastname' => 'Nava',
                'maternal_lastname' => 'Gonzalez',
                'full_name' => 'RAFAEL ANTONIO NAVA GONZALEZ',
                'email' => 'rafael.gonzalez@keyquimica.com',
                'birth_date' => '1993-06-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 168,
                'name' => 'Omar Giovanni',
                'paternal_lastname' => 'Soto',
                'maternal_lastname' => 'Guerrero',
                'full_name' => 'OMAR GIOVANNI SOTO GUERRERO',
                'email' => 'omar.soto@keyquimica.com',
                'birth_date' => '1996-11-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 169,
                'name' => 'Jose Humberto',
                'paternal_lastname' => 'Hoy',
                'maternal_lastname' => 'Lopez',
                'full_name' => 'JOSE HUMBERTO HOY LOPEZ',
                'email' => 'jose.hoy@keyquimica.com',
                'birth_date' => '1989-02-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 170,
                'name' => 'Julio Cesar',
                'paternal_lastname' => 'Martinez',
                'maternal_lastname' => 'Gonzalez',
                'full_name' => 'JULIO CESAR MARTINEZ GONZALEZ',
                'email' => 'julio.martinez@keyquimica.com',
                'birth_date' => '1984-11-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 171,
                'name' => 'Rodrigo',
                'paternal_lastname' => 'Martinez',
                'maternal_lastname' => 'Dominguez',
                'full_name' => 'RODRIGO MARTINEZ DOMINGUEZ',
                'email' => 'rodrigo.martinez@keyquimica.com',
                'birth_date' => '2003-11-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 172,
                'name' => 'Joshio Edmundo',
                'paternal_lastname' => 'Navarro',
                'maternal_lastname' => 'Casillas',
                'full_name' => 'JOSHIO EDMUNDO NAVARRO CASILLAS',
                'email' => 'joshio.navarro@keyquimica.com',
                'birth_date' => '1998-01-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 173,
                'name' => 'Jose Humberto',
                'paternal_lastname' => 'Castro',
                'maternal_lastname' => 'Castro',
                'full_name' => 'JOSE HUMBERTO CASTRO CASTRO',
                'email' => 'humberto.castro@keyquimica.com',
                'birth_date' => '1971-03-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 174,
                'name' => 'Carlos Francisco',
                'paternal_lastname' => 'Carreon',
                'maternal_lastname' => 'Castruita',
                'full_name' => 'CARLOS FRANCISCO CARREON CASTRUITA',
                'email' => 'carlos.castruita@keyquimica.com',
                'birth_date' => '1999-04-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 175,
                'name' => 'Jose Angel',
                'paternal_lastname' => 'Luna',
                'maternal_lastname' => 'Chavez',
                'full_name' => 'JOSE ANGEL LUNA CHAVEZ',
                'email' => 'jose.luna@keyquimica.com',
                'birth_date' => '1979-01-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 176,
                'name' => 'Gonzalo Abraham',
                'paternal_lastname' => 'Macias',
                'maternal_lastname' => 'Davalos',
                'full_name' => 'GONZALO ABRAHAM MACIAS DAVALOS',
                'email' => 'gonzalo.macias@keyquimica.com.mx',
                'birth_date' => '1994-10-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 177,
                'name' => 'Juan Carlos',
                'paternal_lastname' => 'Coronado',
                'maternal_lastname' => 'Ledezma',
                'full_name' => 'JUAN CARLOS CORONADO LEDEZMA',
                'email' => 'juan.coronado@keyquimica.com',
                'birth_date' => '1983-06-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 178,
                'name' => 'Jesus Antonio',
                'paternal_lastname' => 'Reynosa',
                'maternal_lastname' => 'Espinoza',
                'full_name' => 'JESUS ANTONIO REYNOSA ESPINOZA',
                'email' => 'jesus.reynosa@keyquimica.com',
                'birth_date' => '1994-06-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 179,
                'name' => 'Carlos Alberto',
                'paternal_lastname' => 'Marroquin',
                'maternal_lastname' => 'Garibay',
                'full_name' => 'CARLOS ALBERTO MARROQUIN GARIBAY',
                'email' => 'carlos.marroquin@keyquimica.com',
                'birth_date' => '1974-05-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 180,
                'name' => 'Miguel Angel',
                'paternal_lastname' => 'Castillo',
                'maternal_lastname' => 'Honorato',
                'full_name' => 'MIGUEL ANGEL CASTILLO HONORATO',
                'email' => 'miguel.castillo@keyquimica.com',
                'birth_date' => '1977-12-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 181,
                'name' => 'Eduardo',
                'paternal_lastname' => 'Alvarez',
                'maternal_lastname' => 'Sedano',
                'full_name' => 'EDUARDO ALVAREZ SEDANO',
                'email' => 'eduardo.alvarez@keyquimica.com',
                'birth_date' => '1990-11-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 182,
                'name' => 'Aaron Moises',
                'paternal_lastname' => 'Delgado',
                'maternal_lastname' => 'Gaona',
                'full_name' => 'AARON MOISES DELGADO GAONA',
                'email' => 'aaron.delgado@keyquimica.com',
                'birth_date' => '2000-07-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 183,
                'name' => 'Veronica Teodora San',
                'paternal_lastname' => 'Miguel',
                'maternal_lastname' => 'Acosta',
                'full_name' => 'VERONICA TEODORA SAN MIGUEL ACOSTA',
                'email' => 'veronica.sanmiguel@keyquimica.com',
                'birth_date' => '1975-09-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 184,
                'name' => 'Jose Luis',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'Hinojosa',
                'full_name' => 'GARCIA HINOJOSA JOSE LUIS',
                'email' => 'luizgarzia20@hotmail.com',
                'birth_date' => '1973-02-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 185,
                'name' => 'Cano',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Bricio',
                'full_name' => 'CANO HERNANDEZ BRICIO',
                'email' => 'bcano@hydrocontrol.com.mx',
                'birth_date' => '1980-05-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 186,
                'name' => 'Rocha Ruiz',
                'paternal_lastname' => 'Juan',
                'maternal_lastname' => 'Hugo',
                'full_name' => 'ROCHA RUIZ JUAN HUGO',
                'email' => 'hydrohugocsl@hotmail.com',
                'birth_date' => '1973-07-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 187,
                'name' => 'Martinez',
                'paternal_lastname' => 'Palacios',
                'maternal_lastname' => 'Gervacio',
                'full_name' => 'MARTINEZ PALACIOS GERVACIO',
                'email' => 'gervacio0679@gmail.com',
                'birth_date' => '1978-06-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 188,
                'name' => 'Montano',
                'paternal_lastname' => 'Landa',
                'maternal_lastname' => 'Servando',
                'full_name' => 'MONTANO LANDA SERVANDO',
                'email' => 'servando.montano@hydrocon.com.mx',
                'birth_date' => '1982-09-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 189,
                'name' => 'Montoya',
                'paternal_lastname' => 'Ortiz',
                'maternal_lastname' => 'Reyvel',
                'full_name' => 'MONTOYA ORTIZ REYVEL',
                'email' => 'reyvelmontoya@hotmail.com',
                'birth_date' => '1986-10-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 190,
                'name' => 'Varela Olvera',
                'paternal_lastname' => 'Luis',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'VARELA OLVERA LUIS ALBERTO',
                'email' => 'luis-alberto1410@hotmail.com',
                'birth_date' => '1985-02-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 191,
                'name' => 'Tirado',
                'paternal_lastname' => 'Ochoa',
                'maternal_lastname' => 'Modesto',
                'full_name' => 'TIRADO OCHOA MODESTO',
                'email' => 'tito221049@gmail.com',
                'birth_date' => '1986-03-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 192,
                'name' => 'Carlos',
                'paternal_lastname' => 'Rangel',
                'maternal_lastname' => 'Gonzalez',
                'full_name' => 'RANGEL GONZALEZ CARLOS',
                'email' => 'carlos.rangel@hydrocon.com.mx',
                'birth_date' => '1990-07-31',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 193,
                'name' => 'Nuñez',
                'paternal_lastname' => 'Estrada',
                'maternal_lastname' => 'Claudia',
                'full_name' => 'NUÑEZ ESTRADA CLAUDIA',
                'email' => 'claudia.nunez@hydrocon.com.mx',
                'birth_date' => '1985-01-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 194,
                'name' => 'Victor',
                'paternal_lastname' => 'Teniente',
                'maternal_lastname' => 'Villanueva',
                'full_name' => 'TENIENTE VILLANUEVA VICTOR',
                'email' => 'victor.teniente@hydrocon.com.mx',
                'birth_date' => '1978-03-22',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 195,
                'name' => 'Israel',
                'paternal_lastname' => 'Luna',
                'maternal_lastname' => 'Jimenez',
                'full_name' => 'LUNA JIMENEZ ISRAEL',
                'email' => 'edwinluna_14@hotmail.com',
                'birth_date' => '1983-12-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 196,
                'name' => 'Javier',
                'paternal_lastname' => 'Pineda',
                'maternal_lastname' => 'Marmolejo',
                'full_name' => 'PINEDA MARMOLEJO JAVIER',
                'email' => 'pinedajavier1@hotmail.com',
                'birth_date' => '1987-07-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 197,
                'name' => 'Adrian',
                'paternal_lastname' => 'Mejia',
                'maternal_lastname' => 'Loza',
                'full_name' => 'MEJIA LOZA ADRIAN',
                'email' => 'adrian.mejia@hydrocon.com.mx',
                'birth_date' => '1989-07-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 198,
                'name' => 'Victor Manuel',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Diaz',
                'full_name' => 'HERNANDEZ DIAZ VICTOR MANUEL',
                'email' => 'vicmanhd69@hotmail.com',
                'birth_date' => '1988-10-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 199,
                'name' => 'Reyes Garcia',
                'paternal_lastname' => 'Hugo',
                'maternal_lastname' => 'Hanibal',
                'full_name' => 'REYES GARCIA HUGO HANIBAL',
                'email' => 'ugoanibal3@hotmail.com',
                'birth_date' => '1986-12-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 200,
                'name' => 'Armando',
                'paternal_lastname' => 'Rubio',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'RUBIO GARCIA ARMANDO',
                'email' => 'armando.rubio@hydrocon.com.mx',
                'birth_date' => '1989-01-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];
    }
}
