<?php

namespace App\Imports;
use Carbon\Carbon;
class UsersMedicalAttentionFive
{
    public static function data(): array
    {
        $now = Carbon::now();
        $password = bcrypt('Pa$$word');
        return [            
            [
                'id' => 500,
                'name' => 'Ureña Morales',
                'paternal_lastname' => 'Francisco',
                'maternal_lastname' => 'Tadeo',
                'full_name' => 'UREÑA MORALES FRANCISCO TADEO',
                'email' => 'tadeourenamorales@gmail.com',
                'birth_date' => '1982-03-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 501,
                'name' => 'Fuentes Treviño',
                'paternal_lastname' => 'Roberto',
                'maternal_lastname' => 'Gael',
                'full_name' => 'FUENTES TREVIÑO ROBERTO GAEL',
                'email' => 'robertogaelft@gmail.com',
                'birth_date' => '1982-04-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 502,
                'name' => 'Garza',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Samuel',
                'full_name' => 'GARZA GONZALEZ SAMUEL',
                'email' => 'samy12garza@gmail.com',
                'birth_date' => '1995-03-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 503,
                'name' => 'Rojas Escobar',
                'paternal_lastname' => 'Noe',
                'maternal_lastname' => 'Mauricio',
                'full_name' => 'ROJAS ESCOBAR NOE MAURICIO',
                'email' => 'mauriciorojas018@hotmail.com',
                'birth_date' => '1983-04-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 504,
                'name' => 'Felipe De Jesus',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Castillo',
                'full_name' => 'GONZALEZ CASTILLO FELIPE DE JESUS',
                'email' => 'dotther.x@live.com.mx',
                'birth_date' => '1976-04-22',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 505,
                'name' => 'Domingo',
                'paternal_lastname' => 'Enrique',
                'maternal_lastname' => 'Dionicio',
                'full_name' => 'DOMINGO ENRIQUE DIONICIO',
                'email' => 'domingoenriquedionicio@gmail.com',
                'birth_date' => '1962-08-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 506,
                'name' => 'Vazquez Badillo',
                'paternal_lastname' => 'Eduardo',
                'maternal_lastname' => 'Guadalupe',
                'full_name' => 'VAZQUEZ BADILLO EDUARDO GUADALUPE',
                'email' => 'eduardovazquezbadillo@gmail.cim',
                'birth_date' => '1963-12-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 507,
                'name' => 'Rogelio',
                'paternal_lastname' => 'Xochihua',
                'maternal_lastname' => 'Perez',
                'full_name' => 'XOCHIHUA PEREZ ROGELIO',
                'email' => 'rogelioxochihua781@gmail.com',
                'birth_date' => '1969-09-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 508,
                'name' => 'Gonzalez',
                'paternal_lastname' => 'Araujo',
                'maternal_lastname' => 'Joel',
                'full_name' => 'GONZALEZ ARAUJO JOEL',
                'email' => 'gonzalezaraujojoel@gmail.com',
                'birth_date' => '1972-09-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 509,
                'name' => 'Rojas Escobar',
                'paternal_lastname' => 'Efrain',
                'maternal_lastname' => 'Ulises',
                'full_name' => 'ROJAS ESCOBAR EFRAIN ULISES',
                'email' => 'efrainulises29@gmail.com',
                'birth_date' => '1977-08-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 510,
                'name' => 'Contreras',
                'paternal_lastname' => 'Contreras',
                'maternal_lastname' => 'Elisa',
                'full_name' => 'CONTRERAS CONTRERAS ELISA',
                'email' => null,
                'birth_date' => '1988-08-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 511,
                'name' => 'Veronica',
                'paternal_lastname' => 'Aguirre',
                'maternal_lastname' => 'Iracheta',
                'full_name' => 'AGUIRRE IRACHETA VERONICA',
                'email' => null,
                'birth_date' => '1993-01-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 512,
                'name' => 'Guerra',
                'paternal_lastname' => 'Contreras',
                'maternal_lastname' => 'Adriana',
                'full_name' => 'GUERRA CONTRERAS ADRIANA',
                'email' => 'adrianaymanu2016@gmail.com',
                'birth_date' => '1986-12-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 513,
                'name' => 'Hernandez Cadena',
                'paternal_lastname' => 'Evangelina',
                'maternal_lastname' => 'Gabriela',
                'full_name' => 'HERNANDEZ CADENA EVANGELINA GABRIELA',
                'email' => 'gaby70amor@gmail.com',
                'birth_date' => '1971-06-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 514,
                'name' => 'Gonzalez Robles',
                'paternal_lastname' => 'Beatriz',
                'maternal_lastname' => 'Adriana',
                'full_name' => 'GONZALEZ ROBLES BEATRIZ ADRIANA',
                'email' => null,
                'birth_date' => '1995-09-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 515,
                'name' => 'Quezada',
                'paternal_lastname' => 'Cervantes',
                'maternal_lastname' => 'Claudia',
                'full_name' => 'QUEZADA CERVANTES CLAUDIA',
                'email' => null,
                'birth_date' => '1972-12-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
