<?php

namespace App\Imports;
use Carbon\Carbon;
class UsersMedicalAttentionOne
{
    public static function data(): array
    {
        $now = Carbon::now();
        $password = bcrypt('Pa$$word');
        return [
            [
                'id' => 1,
                'name' => 'Alfredo',
                'paternal_lastname' => 'Reyna',
                'maternal_lastname' => 'Gamez',
                'full_name' => 'ALFREDO REYNA GAMEZ',
                'email' => 'alfredo.reyna@keyquimica.com',
                'birth_date' => '1959-01-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Luis Francisco',
                'paternal_lastname' => 'Puente',
                'maternal_lastname' => 'Moreno',
                'full_name' => 'LUIS FRANCISCO PUENTE MORENO',
                'email' => 'luis.puente@keyquimica.com',
                'birth_date' => '1976-07-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Francisco Javier',
                'paternal_lastname' => 'Geronimo',
                'maternal_lastname' => 'Dominguez',
                'full_name' => 'FRANCISCO JAVIER GERONIMO DOMINGUEZ',
                'email' => 'francisco.geronimo@keyquimica.com',
                'birth_date' => '1968-10-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Francisco',
                'paternal_lastname' => 'Acevedo',
                'maternal_lastname' => 'Olivo',
                'full_name' => 'FRANCISCO ACEVEDO OLIVO',
                'email' => 'yasmin.cardiel@key.com.mx',
                'birth_date' => '1963-04-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Ernesto',
                'paternal_lastname' => 'Estrada',
                'maternal_lastname' => 'Castañeda',
                'full_name' => 'ERNESTO ESTRADA CASTAÑEDA',
                'email' => 'mayela.moreno@key.com.mx',
                'birth_date' => '1976-07-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'Jorge',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Ramirez',
                'full_name' => 'JORGE GONZALEZ RAMIREZ',
                'email' => 'lesley.carrera@key.com.mx',
                'birth_date' => '1980-02-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'Carlos',
                'paternal_lastname' => 'Grajales',
                'maternal_lastname' => 'Casas',
                'full_name' => 'CARLOS GRAJALES CASAS',
                'email' => 'rebeca.palomo@key.com.mx',
                'birth_date' => '1969-11-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'Jose De Jesus',
                'paternal_lastname' => 'Saldaña',
                'maternal_lastname' => 'Valverde',
                'full_name' => 'JOSE DE JESUS SALDAÑA VALVERDE',
                'email' => 'olivia.olloqui@key.com.mx',
                'birth_date' => '1974-11-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'Armando',
                'paternal_lastname' => 'Montoya',
                'maternal_lastname' => 'Rangel',
                'full_name' => 'ARMANDO MONTOYA RANGEL',
                'email' => 'nereida.salas@key.com.mx',
                'birth_date' => '1969-05-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'Gustavo',
                'paternal_lastname' => 'Lopez',
                'maternal_lastname' => 'Rosete',
                'full_name' => 'GUSTAVO LOPEZ ROSETE',
                'email' => 'yadira.torrealba@key.com.mx',
                'birth_date' => '1968-08-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'Alvaro',
                'paternal_lastname' => 'Quintana',
                'maternal_lastname' => 'Carrasco',
                'full_name' => 'ALVARO QUINTANA CARRASCO',
                'email' => 'edgar.alvarez@key.com.mx',
                'birth_date' => '1974-11-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'name' => 'Juvenal',
                'paternal_lastname' => 'Betancourt',
                'maternal_lastname' => 'Herrera',
                'full_name' => 'JUVENAL BETANCOURT HERRERA',
                'email' => 'juvenal.betancourt@keyquimica.com',
                'birth_date' => '1974-01-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'Rafael',
                'paternal_lastname' => 'Aviña',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'RAFAEL AVIÑA GARCIA',
                'email' => 'elizabeth.amaro@key.com.mx',
                'birth_date' => '1965-10-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'Fabian',
                'paternal_lastname' => 'Ruiz',
                'maternal_lastname' => 'Solis',
                'full_name' => 'FABIAN RUIZ SOLIS',
                'email' => 'fabian.ruiz@keyquimica.com',
                'birth_date' => '1978-02-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'name' => 'Fabian',
                'paternal_lastname' => 'Giorgana',
                'maternal_lastname' => 'Mazariego',
                'full_name' => 'FABIAN GIORGANA MAZARIEGO',
                'email' => 'sergio.flores@key.com.mx',
                'birth_date' => '1972-12-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'name' => 'Alejandro',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'Aragon',
                'full_name' => 'ALEJANDRO GARCIA ARAGON',
                'email' => 'alejandro.garcia@keyquimica.com',
                'birth_date' => '1973-02-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'name' => 'Leonardo',
                'paternal_lastname' => 'Pacheco',
                'maternal_lastname' => 'Ramos',
                'full_name' => 'LEONARDO PACHECO RAMOS',
                'email' => 'anayeli.gonzalez@key.com.mx',
                'birth_date' => '1975-03-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'name' => 'Manuel',
                'paternal_lastname' => 'Salgado',
                'maternal_lastname' => 'Morua',
                'full_name' => 'MANUEL SALGADO MORUA',
                'email' => 'manuel.salgado@keyquimica.com',
                'birth_date' => '1987-02-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'name' => 'Isaias',
                'paternal_lastname' => 'Torres',
                'maternal_lastname' => 'Leyva',
                'full_name' => 'ISAIAS TORRES LEYVA',
                'email' => 'noe.sanchez@key.com.mx',
                'birth_date' => '1967-08-31',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'name' => 'Carlos Roman',
                'paternal_lastname' => 'Dzul',
                'maternal_lastname' => 'Chi',
                'full_name' => 'CARLOS ROMAN DZUL CHI',
                'email' => 'carlos.dzul@keyquimica.com',
                'birth_date' => '1972-08-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'name' => 'Oscar',
                'paternal_lastname' => 'Reynoso',
                'maternal_lastname' => 'Serna',
                'full_name' => 'OSCAR REYNOSO SERNA',
                'email' => 'erika.galvan@key.com.mx',
                'birth_date' => '1966-10-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'name' => 'Cesario',
                'paternal_lastname' => 'Olvera',
                'maternal_lastname' => 'Zepeda',
                'full_name' => 'CESARIO OLVERA ZEPEDA',
                'email' => 'araceli.gomez@key.com.mx',
                'birth_date' => '1978-03-22',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'name' => 'Jose Lorenzo',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Zamarripa',
                'full_name' => 'JOSE LORENZO HERNANDEZ ZAMARRIPA',
                'email' => 'rossana.hernandez@key.com.mx',
                'birth_date' => '1978-09-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'name' => 'Ruben',
                'paternal_lastname' => 'Ruiz',
                'maternal_lastname' => 'Ramon',
                'full_name' => 'RUBEN RUIZ RAMON',
                'email' => 'ruben.ruiz@keyquimica.com',
                'birth_date' => '1963-02-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'name' => 'Juan Carlos',
                'paternal_lastname' => 'Figueroa',
                'maternal_lastname' => 'Morales',
                'full_name' => 'JUAN CARLOS FIGUEROA MORALES',
                'email' => 'rocio.galicia@key.com.mx',
                'birth_date' => '1974-08-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'name' => 'Omar',
                'paternal_lastname' => 'Ibarra',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'OMAR IBARRA GARCIA',
                'email' => 'brenda.almaraz@key.com.mx',
                'birth_date' => '1988-05-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'name' => 'Vicente Emilio',
                'paternal_lastname' => 'Noyola',
                'maternal_lastname' => 'Mariche',
                'full_name' => 'VICENTE EMILIO NOYOLA MARICHE',
                'email' => 'sofia.diaz@key.com.mx',
                'birth_date' => '1966-04-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'name' => 'Rigoberto',
                'paternal_lastname' => 'De Santiago',
                'maternal_lastname' => 'Alonso',
                'full_name' => 'RIGOBERTO DE SANTIAGO ALONSO',
                'email' => 'rigoberto.desantiago@keyquimica.com',
                'birth_date' => '1975-06-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'name' => 'Jose Alfredo',
                'paternal_lastname' => 'Montejo',
                'maternal_lastname' => 'Menendez',
                'full_name' => 'JOSE ALFREDO MONTEJO MENENDEZ',
                'email' => 'jose.montejo@key.com.mx',
                'birth_date' => '1971-04-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'name' => 'Alejandro',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Gutierrez',
                'full_name' => 'ALEJANDRO HERNANDEZ GUTIERREZ',
                'email' => 'erika.barbosa@key.com.mx',
                'birth_date' => '1975-06-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'name' => 'Hipolito',
                'paternal_lastname' => 'Lopez',
                'maternal_lastname' => 'Rosario',
                'full_name' => 'HIPOLITO LOPEZ ROSARIO',
                'email' => 'hipolito.lopez@keyquimica.com',
                'birth_date' => '1971-04-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'name' => 'Omar',
                'paternal_lastname' => 'Sesma',
                'maternal_lastname' => 'Cantillo',
                'full_name' => 'OMAR SESMA CANTILLO',
                'email' => 'nelly.vargas@key.com.mx',
                'birth_date' => '1974-09-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'name' => 'Antonio',
                'paternal_lastname' => 'Diaz',
                'maternal_lastname' => 'Zarate',
                'full_name' => 'ANTONIO DIAZ ZARATE',
                'email' => 'antonio.diaz@key.com.mx',
                'birth_date' => '1965-05-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'name' => 'Jose Francisco',
                'paternal_lastname' => 'Sanchez',
                'maternal_lastname' => 'Zapata',
                'full_name' => 'JOSE FRANCISCO SANCHEZ ZAPATA',
                'email' => 'jose.sanchez@keyquimica.com',
                'birth_date' => '1984-10-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'name' => 'Luis Amado',
                'paternal_lastname' => 'Camberos',
                'maternal_lastname' => 'Gascon',
                'full_name' => 'LUIS AMADO CAMBEROS GASCON',
                'email' => 'diana.serna@key.com.mx',
                'birth_date' => '1966-05-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'name' => 'Ignacio',
                'paternal_lastname' => 'Soto',
                'maternal_lastname' => 'Soto',
                'full_name' => 'IGNACIO SOTO SOTO',
                'email' => 'ignacio.soto@keyquimica.com',
                'birth_date' => '1976-10-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'name' => 'Jesus',
                'paternal_lastname' => 'Palacios',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'JESUS PALACIOS MARTINEZ',
                'email' => 'jesus.palacios@keyquimica.com',
                'birth_date' => '1976-11-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'name' => 'Samuel',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'SAMUEL GARCIA GARCIA',
                'email' => 'samuel.garcia@keyquimica.com',
                'birth_date' => '1966-07-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'name' => 'Francisco Antonio',
                'paternal_lastname' => 'Flores',
                'maternal_lastname' => 'Razo',
                'full_name' => 'FRANCISCO ANTONIO FLORES RAZO',
                'email' => 'francisco.flores@keyquimica.com',
                'birth_date' => '1986-09-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'name' => 'Raul',
                'paternal_lastname' => 'Flores',
                'maternal_lastname' => 'Diaz',
                'full_name' => 'RAUL FLORES DIAZ',
                'email' => 'raul.flores@key.com.mx',
                'birth_date' => '1972-11-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'name' => 'Leobardo',
                'paternal_lastname' => 'Ramirez',
                'maternal_lastname' => 'Mayorga',
                'full_name' => 'LEOBARDO RAMIREZ MAYORGA',
                'email' => 'leobardo.ramirez@keyquimica.com',
                'birth_date' => '1976-05-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'name' => 'Jose Luis',
                'paternal_lastname' => 'Cota',
                'maternal_lastname' => 'Cabanillas',
                'full_name' => 'JOSE LUIS COTA CABANILLAS',
                'email' => 'daysi.perez@key.com.mx',
                'birth_date' => '1973-03-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'name' => 'Jonathan',
                'paternal_lastname' => 'Lopez',
                'maternal_lastname' => 'Feliciano',
                'full_name' => 'JONATHAN LOPEZ FELICIANO',
                'email' => 'daniel.fabian@key.com.mx',
                'birth_date' => '1966-11-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'name' => 'Aldegundo',
                'paternal_lastname' => 'Saavedra',
                'maternal_lastname' => 'Sanchez',
                'full_name' => 'ALDEGUNDO SAAVEDRA SANCHEZ',
                'email' => 'alde07sasa@gmail.com',
                'birth_date' => '1976-09-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'name' => 'Brandon Saul',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Rios',
                'full_name' => 'BRANDON SAUL GONZALEZ RIOS',
                'email' => 'diana.serna@key.com.mx',
                'birth_date' => '1994-05-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'name' => 'Miguel',
                'paternal_lastname' => 'Aceves',
                'maternal_lastname' => 'Molina',
                'full_name' => 'MIGUEL ACEVES MOLINA',
                'email' => 'miguel.aceves@keyquimica.com',
                'birth_date' => '1978-09-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'name' => 'Jose Luis',
                'paternal_lastname' => 'Ibarra',
                'maternal_lastname' => 'Arzola',
                'full_name' => 'JOSE LUIS IBARRA ARZOLA',
                'email' => 'jose.ibarra@keyquimica.com',
                'birth_date' => '1968-08-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'name' => 'Fernando',
                'paternal_lastname' => 'Rangel',
                'maternal_lastname' => 'Souza',
                'full_name' => 'FERNANDO RANGEL SOUZA',
                'email' => 'fernando.rangel@keyquimica.com',
                'birth_date' => '1979-04-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'name' => 'Luis Adrian',
                'paternal_lastname' => 'Valenzuela',
                'maternal_lastname' => 'Rodriguez',
                'full_name' => 'LUIS ADRIAN VALENZUELA RODRIGUEZ',
                'email' => 'luis.valenzuela@keyquimica.com',
                'birth_date' => '1992-08-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'name' => 'Irving De Jesus',
                'paternal_lastname' => 'Velazquez',
                'maternal_lastname' => 'Gonzalez',
                'full_name' => 'IRVING DE JESUS VELAZQUEZ GONZALEZ',
                'email' => 'irving.velazquez@keyquimica.com',
                'birth_date' => '1998-07-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'name' => 'Jose Adrian',
                'paternal_lastname' => 'Martinez',
                'maternal_lastname' => 'Villanueva',
                'full_name' => 'JOSE ADRIAN MARTINEZ VILLANUEVA',
                'email' => 'jose.martinez@keyquimica.com',
                'birth_date' => '1977-01-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'name' => 'Brayan Alexis',
                'paternal_lastname' => 'Samaniego',
                'maternal_lastname' => 'Vargas',
                'full_name' => 'BRAYAN ALEXIS SAMANIEGO VARGAS',
                'email' => 'basv0410@gmail.com',
                'birth_date' => '2000-04-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'name' => 'Eduardo Gabriel',
                'paternal_lastname' => 'Longoria',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'EDUARDO GABRIEL LONGORIA MARTINEZ',
                'email' => 'eduardo.longoria@keyquimica.com',
                'birth_date' => '1994-01-31',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'name' => 'Jose Emiliano',
                'paternal_lastname' => 'Guajardo',
                'maternal_lastname' => 'Armendariz',
                'full_name' => 'JOSE EMILIANO GUAJARDO ARMENDARIZ',
                'email' => 'ja0857793@gmail.com',
                'birth_date' => '2000-02-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'name' => 'Elpidio',
                'paternal_lastname' => 'Flores',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'ELPIDIO FLORES MARTINEZ',
                'email' => 'elpi9023@gmail.com',
                'birth_date' => '1990-12-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'name' => 'Julio Antonio',
                'paternal_lastname' => 'Cruz',
                'maternal_lastname' => 'De La Cruz',
                'full_name' => 'JULIO ANTONIO CRUZ DE LA CRUZ',
                'email' => 'julio.cruz@keyquimica.com',
                'birth_date' => '1975-06-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'name' => 'Carlos Alberto',
                'paternal_lastname' => 'Luevano',
                'maternal_lastname' => 'Ramos',
                'full_name' => 'CARLOS ALBERTO LUEVANO RAMOS',
                'email' => 'lesley.carrera@key.com.mx',
                'birth_date' => '1988-11-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'name' => 'Gabriel',
                'paternal_lastname' => 'Bonilla',
                'maternal_lastname' => 'Capilla',
                'full_name' => 'GABRIEL BONILLA CAPILLA',
                'email' => 'gabriel.bonilla@keyquimica.com',
                'birth_date' => '1986-03-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'name' => 'Jesus Heriberto',
                'paternal_lastname' => 'Escobar',
                'maternal_lastname' => 'Alcala',
                'full_name' => 'JESUS HERIBERTO ESCOBAR ALCALA',
                'email' => 'jesus.escobar@keyquimica.com',
                'birth_date' => '1971-01-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'name' => 'Paula',
                'paternal_lastname' => 'Navarro',
                'maternal_lastname' => 'Romo',
                'full_name' => 'PAULA NAVARRO ROMO',
                'email' => 'pe170917@gmail.com',
                'birth_date' => '1974-02-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'name' => 'Victor Alfonso',
                'paternal_lastname' => 'Caballero',
                'maternal_lastname' => 'Dzul',
                'full_name' => 'VICTOR ALFONSO CABALLERO DZUL',
                'email' => 'victor.caballero@keyquimica.com',
                'birth_date' => '1984-10-31',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'name' => 'Jorge',
                'paternal_lastname' => 'Alegria',
                'maternal_lastname' => 'Millan',
                'full_name' => 'JORGE ALEGRIA MILLAN',
                'email' => 'jorge.alegria@keyquimica.com',
                'birth_date' => '1978-04-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 63,
                'name' => 'Marco Antonio',
                'paternal_lastname' => 'Ramirez',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'MARCO ANTONIO RAMIREZ GARCIA',
                'email' => 'marco.ramirez@keyquimica.com',
                'birth_date' => '1979-10-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 64,
                'name' => 'Nohemi',
                'paternal_lastname' => 'Gallegos',
                'maternal_lastname' => 'Reyna',
                'full_name' => 'NOHEMI GALLEGOS REYNA',
                'email' => 'gallegosnohemi47@gmail.com',
                'birth_date' => '1969-03-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 65,
                'name' => 'Oswaldo Rafael Mendoza',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'De Leon',
                'full_name' => 'OSWALDO RAFAEL MENDOZA GARCIA DE LEON',
                'email' => 'oswaldo191070@gmail.com',
                'birth_date' => '1970-10-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 66,
                'name' => 'Israel',
                'paternal_lastname' => 'Rojas',
                'maternal_lastname' => 'Cayetano',
                'full_name' => 'ISRAEL ROJAS CAYETANO',
                'email' => 'israel.rojas@keyquimica.com',
                'birth_date' => '1985-05-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 67,
                'name' => 'Rafael',
                'paternal_lastname' => 'Gutierrez',
                'maternal_lastname' => 'Gutierrez',
                'full_name' => 'RAFAEL GUTIERREZ GUTIERREZ',
                'email' => 'rafael.gutierrez@keyquimica.com',
                'birth_date' => '1980-10-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 68,
                'name' => 'Diana Patricia',
                'paternal_lastname' => 'Castelan',
                'maternal_lastname' => 'Juarez',
                'full_name' => 'DIANA PATRICIA CASTELAN JUAREZ',
                'email' => 'diana.castelan@keyquimica.com',
                'birth_date' => '1977-03-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 69,
                'name' => 'Juan Gualberto',
                'paternal_lastname' => 'Mireles',
                'maternal_lastname' => 'Ramirez',
                'full_name' => 'JUAN GUALBERTO MIRELES RAMIREZ',
                'email' => 'juan.mireles@keyquimica.com',
                'birth_date' => '1979-07-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 70,
                'name' => 'Jose Pedro',
                'paternal_lastname' => 'Coronel',
                'maternal_lastname' => 'Olivares',
                'full_name' => 'JOSE PEDRO CORONEL OLIVARES',
                'email' => 'pedro.rodriguezm@key.com.mx',
                'birth_date' => '1980-10-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 71,
                'name' => 'Victor',
                'paternal_lastname' => 'Chavez',
                'maternal_lastname' => 'Morales',
                'full_name' => 'VICTOR CHAVEZ MORALES',
                'email' => 'victor.chavez@keyquimica.com',
                'birth_date' => '1979-03-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 72,
                'name' => 'Juan Jose',
                'paternal_lastname' => 'Bernal',
                'maternal_lastname' => 'Ruedas',
                'full_name' => 'JUAN JOSE BERNAL RUEDAS',
                'email' => 'claudia.urbina@key.com.mx',
                'birth_date' => '1969-12-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 73,
                'name' => 'Omar',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Lopez',
                'full_name' => 'OMAR GONZALEZ LOPEZ',
                'email' => 'omar.gonzalez@keyquimica.com',
                'birth_date' => '1988-12-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 74,
                'name' => 'Nelson Michel',
                'paternal_lastname' => 'Ramirez',
                'maternal_lastname' => 'Aleman',
                'full_name' => 'NELSON MICHEL RAMIREZ ALEMAN',
                'email' => 'nelsonaleman2907@gmail.com',
                'birth_date' => '1989-07-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 75,
                'name' => 'Eri Iran',
                'paternal_lastname' => 'May',
                'maternal_lastname' => 'Ballinas',
                'full_name' => 'ERI IRAN MAY BALLINAS',
                'email' => 'nereida.salas@key.com.mx',
                'birth_date' => '1992-06-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 76,
                'name' => 'Jose Fidencio',
                'paternal_lastname' => 'Barron',
                'maternal_lastname' => 'Ruiz',
                'full_name' => 'JOSE FIDENCIO BARRON RUIZ',
                'email' => 'pille3154@gmail.com',
                'birth_date' => '1980-05-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 77,
                'name' => 'Roman',
                'paternal_lastname' => 'Fernandez',
                'maternal_lastname' => 'Martinez',
                'full_name' => 'ROMAN FERNANDEZ MARTINEZ',
                'email' => 'roman.fernandez@keyquimica.com',
                'birth_date' => '1989-10-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 78,
                'name' => 'Cesar David',
                'paternal_lastname' => 'Miranda',
                'maternal_lastname' => 'Alcocer',
                'full_name' => 'CESAR DAVID MIRANDA ALCOCER',
                'email' => '23dhavo@gmail.com',
                'birth_date' => '1993-04-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 79,
                'name' => 'Dagoberto',
                'paternal_lastname' => 'Potenciano',
                'maternal_lastname' => 'Cruz',
                'full_name' => 'DAGOBERTO POTENCIANO CRUZ',
                'email' => 'magneto_1410@hotmail.com',
                'birth_date' => '1989-03-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 80,
                'name' => 'Miguel',
                'paternal_lastname' => 'Rosales',
                'maternal_lastname' => 'Rivera',
                'full_name' => 'MIGUEL ROSALES RIVERA',
                'email' => 'miguel.rosales@keyquimica.com',
                'birth_date' => '1999-09-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 81,
                'name' => 'Francisco Alexandro',
                'paternal_lastname' => 'Flores',
                'maternal_lastname' => '',
                'full_name' => 'ALEXANDRO FLORES FRANCISCO',
                'email' => 'alexandro11flores@gmail.com',
                'birth_date' => '2003-10-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 82,
                'name' => 'Gabriel',
                'paternal_lastname' => 'Torres',
                'maternal_lastname' => 'Moncada',
                'full_name' => 'GABRIEL TORRES MONCADA',
                'email' => 'gabriel.torres@keyquimica.com',
                'birth_date' => '2000-01-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 83,
                'name' => 'Felix Alejandro',
                'paternal_lastname' => 'Higareda',
                'maternal_lastname' => 'Torres',
                'full_name' => 'FELIX ALEJANDRO HIGAREDA TORRES',
                'email' => 'felix.higareda@keyquimica.com',
                'birth_date' => '1995-10-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 84,
                'name' => 'Erick Sinuhe',
                'paternal_lastname' => 'Ramirez',
                'maternal_lastname' => 'Vazquez',
                'full_name' => 'ERICK SINUHE RAMIREZ VAZQUEZ',
                'email' => 'erick.ramirez@keyquimica.com',
                'birth_date' => '1998-06-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 85,
                'name' => 'Jorge Alberto',
                'paternal_lastname' => 'Aguilar',
                'maternal_lastname' => 'Flores',
                'full_name' => 'JORGE ALBERTO AGUILAR FLORES',
                'email' => 'jorge.aguilar@keyquimica.com',
                'birth_date' => '1994-11-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 86,
                'name' => 'Jose Cesar',
                'paternal_lastname' => 'Muñiz',
                'maternal_lastname' => 'Guanajuato',
                'full_name' => 'JOSE CESAR MUÑIZ GUANAJUATO',
                'email' => 'munizcesar528@gmail.com',
                'birth_date' => '1978-02-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 87,
                'name' => 'Juan Antonio',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Galvan',
                'full_name' => 'JUAN ANTONIO HERNANDEZ GALVAN',
                'email' => 'juan.hernandez@key.com.mx',
                'birth_date' => '1990-01-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 88,
                'name' => 'Raul Isaac',
                'paternal_lastname' => 'Monsivais',
                'maternal_lastname' => 'Viera',
                'full_name' => 'RAUL ISAAC MONSIVAIS VIERA',
                'email' => 'raul.monsivais@keyquimica.com',
                'birth_date' => '1986-02-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 89,
                'name' => 'Juan Jose',
                'paternal_lastname' => 'Elizondo',
                'maternal_lastname' => 'Rodriguez',
                'full_name' => 'JUAN JOSE ELIZONDO RODRIGUEZ',
                'email' => 'mayra.arizpe@key.com.mx',
                'birth_date' => '1987-11-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 90,
                'name' => 'Jose Adrian',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'De Dios',
                'full_name' => 'JOSE ADRIAN PEREZ DE DIOS',
                'email' => 'adrian.perez@keyquimica.com',
                'birth_date' => '1990-12-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 91,
                'name' => 'Vidal',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Pinales',
                'full_name' => 'VIDAL HERNANDEZ PINALES',
                'email' => 'vidal.hernandez@keyquimica.com',
                'birth_date' => '1986-11-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 92,
                'name' => 'Vladimir',
                'paternal_lastname' => 'Porfirio',
                'maternal_lastname' => 'Vega',
                'full_name' => 'VLADIMIR PORFIRIO VEGA',
                'email' => 'vladimirporfiriov@gmail.com',
                'birth_date' => '1998-08-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 93,
                'name' => 'Benjamin',
                'paternal_lastname' => 'Chapan',
                'maternal_lastname' => 'Xolio',
                'full_name' => 'BENJAMIN CHAPAN XOLIO',
                'email' => 'lesley.carrera@key.com.mx',
                'birth_date' => '1979-05-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 94,
                'name' => 'Erika Judith',
                'paternal_lastname' => 'Gallegos',
                'maternal_lastname' => 'Godina',
                'full_name' => 'ERIKA JUDITH GALLEGOS GODINA',
                'email' => 'mario.lara@key.com.mx',
                'birth_date' => '1993-10-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 95,
                'name' => 'David Eduardo',
                'paternal_lastname' => 'Macias',
                'maternal_lastname' => 'Moran',
                'full_name' => 'DAVID EDUARDO MACIAS MORAN',
                'email' => 'david.macias@keyquimica.com',
                'birth_date' => '1981-08-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 96,
                'name' => 'Seferino',
                'paternal_lastname' => 'Jimenez',
                'maternal_lastname' => 'Perez',
                'full_name' => 'SEFERINO JIMENEZ PEREZ',
                'email' => 'seferino.jimenez@keyquimica.com',
                'birth_date' => '1993-09-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 97,
                'name' => 'Jesus Alberto',
                'paternal_lastname' => 'Badillo',
                'maternal_lastname' => 'Garcia',
                'full_name' => 'JESUS ALBERTO BADILLO GARCIA',
                'email' => 'jesus.badillo@keyquimica.com',
                'birth_date' => '1989-09-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 98,
                'name' => 'Luis David',
                'paternal_lastname' => 'Gonzalez',
                'maternal_lastname' => 'Dominguez',
                'full_name' => 'LUIS DAVID GONZALEZ DOMINGUEZ',
                'email' => 'luis.gonzalez@keyquimica.com',
                'birth_date' => '1986-04-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 99,
                'name' => 'Arnulfo',
                'paternal_lastname' => 'Reyes',
                'maternal_lastname' => 'Perez',
                'full_name' => 'ARNULFO REYES PEREZ',
                'email' => 'arnulfo.reyes@keyquimica.com',
                'birth_date' => '1977-03-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 100,
                'name' => 'Osiel Eduardo',
                'paternal_lastname' => 'Garcia',
                'maternal_lastname' => 'Lopez',
                'full_name' => 'OSIEL EDUARDO GARCIA LOPEZ',
                'email' => 'lopezosiel124@gmail.com',
                'birth_date' => '1999-03-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];
    }
}
