<?php

namespace App\Imports;
use Carbon\Carbon;
class UsersMedicalAttentionFour
{
    public static function data(): array
    {
        $now = Carbon::now();
        $password = bcrypt('Pa$$word');
        return [            
            [
                'id' => 400,
                'name' => 'Caña Jose',
                'paternal_lastname' => 'Yoloxochilt',
                'maternal_lastname' => 'Nallely',
                'full_name' => 'CAÑA JOSE YOLOXOCHILT NALLELY',
                'email' => 'yoloxochitlnallelycana@gmail.com',
                'birth_date' => '1986-09-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 401,
                'name' => 'Gutierrez Franco',
                'paternal_lastname' => 'Maria',
                'maternal_lastname' => 'Del Rosario',
                'full_name' => 'GUTIERREZ FRANCO MARIA DEL ROSARIO',
                'email' => 'rosariogutierrezfranco@gmail.com',
                'birth_date' => '1986-05-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 402,
                'name' => 'Norberto',
                'paternal_lastname' => 'Luis',
                'maternal_lastname' => 'Longino',
                'full_name' => 'NORBERTO LUIS LONGINO',
                'email' => 'norbertoluislongino@gmail.com',
                'birth_date' => '1977-12-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 403,
                'name' => 'Niño Hernandez',
                'paternal_lastname' => 'Jorge',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'NIÑO HERNANDEZ JORGE ALBERTO',
                'email' => 'jorgeninohernandez@gmail.com',
                'birth_date' => '1981-01-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 404,
                'name' => 'Fernando',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'HERNANDEZ HERNANDEZ FERNANDO',
                'email' => 'isayfer2407@gmail.com',
                'birth_date' => '1977-09-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 405,
                'name' => 'Juan Eduardo',
                'paternal_lastname' => 'Segura',
                'maternal_lastname' => 'Villanueva',
                'full_name' => 'SEGURA VILLANUEVA JUAN EDUARDO',
                'email' => 'esegura157@gmail.com',
                'birth_date' => '1991-06-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 406,
                'name' => 'Dominguez',
                'paternal_lastname' => 'Gomez',
                'maternal_lastname' => 'Griselda',
                'full_name' => 'DOMINGUEZ GOMEZ GRISELDA',
                'email' => 'gris_do25@hotmail.com',
                'birth_date' => '1991-12-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 407,
                'name' => 'Cortes',
                'paternal_lastname' => 'Torres',
                'maternal_lastname' => 'Yesenia',
                'full_name' => 'CORTES TORRES YESENIA',
                'email' => 'yessyqueen133@gmail.com',
                'birth_date' => '1978-09-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 408,
                'name' => 'Gonzalez Antonio',
                'paternal_lastname' => 'Jose',
                'maternal_lastname' => 'Buenaventura',
                'full_name' => 'GONZALEZ ANTONIO JOSE BUENAVENTURA',
                'email' => 'jbuenaventura0404@gmail.com',
                'birth_date' => '1970-12-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 409,
                'name' => 'Juan Manuel',
                'paternal_lastname' => 'Zamora',
                'maternal_lastname' => 'Quintero',
                'full_name' => 'ZAMORA QUINTERO JUAN MANUEL',
                'email' => 'manuelybrianna1@gmail.com',
                'birth_date' => '1994-07-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 410,
                'name' => 'Rodriguez Gamero',
                'paternal_lastname' => 'Claudia',
                'maternal_lastname' => 'Elizabeth',
                'full_name' => 'RODRIGUEZ GAMERO CLAUDIA ELIZABETH',
                'email' => 'claurdz7421@gmail.com',
                'birth_date' => '1998-05-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 411,
                'name' => 'Moreno Rosales',
                'paternal_lastname' => 'Ignacio',
                'maternal_lastname' => 'Guadalupe',
                'full_name' => 'MORENO ROSALES IGNACIO GUADALUPE',
                'email' => 'chacho.moreno123@gmail.com',
                'birth_date' => '1991-02-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 412,
                'name' => 'Jose Maria',
                'paternal_lastname' => 'Villanueva',
                'maternal_lastname' => 'Rivera',
                'full_name' => 'VILLANUEVA RIVERA JOSE MARIA',
                'email' => 'josse_chema_19@hotmail.com',
                'birth_date' => '1994-02-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 413,
                'name' => 'Martinez Garcia',
                'paternal_lastname' => 'Edwin',
                'maternal_lastname' => 'Saul',
                'full_name' => 'MARTINEZ GARCIA EDWIN SAUL',
                'email' => 'edwin2539@gmail.com',
                'birth_date' => '1999-05-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 414,
                'name' => 'Ortiz Merino',
                'paternal_lastname' => 'Alejandro',
                'maternal_lastname' => 'Aldair',
                'full_name' => 'ORTIZ MERINO ALEJANDRO ALDAIR',
                'email' => 'alejandroortizmerino120@gmail.com',
                'birth_date' => '1972-11-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 415,
                'name' => 'Marcos Francisco',
                'paternal_lastname' => 'Treviño',
                'maternal_lastname' => 'Mendez',
                'full_name' => 'TREVIÑO MENDEZ MARCOS FRANCISCO',
                'email' => 'thigcreazy@gmail.com',
                'birth_date' => '1998-07-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 416,
                'name' => 'Mauro',
                'paternal_lastname' => 'Melquiadez',
                'maternal_lastname' => 'Efrain',
                'full_name' => 'MAURO MELQUIADEZ EFRAIN',
                'email' => 'mauroefrain1993@gmail.com',
                'birth_date' => '1992-05-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 417,
                'name' => 'Garcia Garcia',
                'paternal_lastname' => 'Gustavo',
                'maternal_lastname' => 'Adolfo',
                'full_name' => 'GARCIA GARCIA GUSTAVO ADOLFO',
                'email' => 'z.9.0.gustavo.garcia@gmail.com',
                'birth_date' => '1991-11-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 418,
                'name' => 'Salazar Herrera',
                'paternal_lastname' => 'Kevin',
                'maternal_lastname' => 'Aldair',
                'full_name' => 'SALAZAR HERRERA KEVIN ALDAIR',
                'email' => 'kevinaldairsalazar2807@gmail.com',
                'birth_date' => '1993-10-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 419,
                'name' => 'Oscar Israel',
                'paternal_lastname' => 'Sanchez',
                'maternal_lastname' => 'Balderas',
                'full_name' => 'SANCHEZ BALDERAS OSCAR ISRAEL',
                'email' => 'tade1408@gmail.com',
                'birth_date' => '1990-07-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 420,
                'name' => 'Miguel Angel',
                'paternal_lastname' => 'Vallejo',
                'maternal_lastname' => 'Cuellar',
                'full_name' => 'VALLEJO CUELLAR MIGUEL ANGEL',
                'email' => 'miguelvallejo724@gmail.com',
                'birth_date' => '1996-05-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 421,
                'name' => 'Zaleta',
                'paternal_lastname' => 'Vazquez',
                'maternal_lastname' => 'Ruben',
                'full_name' => 'ZALETA VAZQUEZ RUBEN',
                'email' => 'loredeltoro126@gmail.com',
                'birth_date' => '1978-10-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 422,
                'name' => 'Mireles Orta',
                'paternal_lastname' => 'Laura',
                'maternal_lastname' => 'Iraida',
                'full_name' => 'MIRELES ORTA LAURA IRAIDA',
                'email' => 'laurairaida78@gmail.com',
                'birth_date' => '1997-06-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 423,
                'name' => 'Juan Carlos',
                'paternal_lastname' => 'Ontiveros',
                'maternal_lastname' => 'Ramirez',
                'full_name' => 'ONTIVEROS RAMIREZ JUAN CARLOS',
                'email' => 'cr4207903@gmail.com',
                'birth_date' => '1995-02-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 424,
                'name' => 'Jesus Alejandro',
                'paternal_lastname' => 'Valdes',
                'maternal_lastname' => 'Ortega',
                'full_name' => 'VALDES ORTEGA JESUS ALEJANDRO',
                'email' => 'jesusvalort92@gmail.com',
                'birth_date' => '1987-05-26',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 425,
                'name' => 'Ortega Torres',
                'paternal_lastname' => 'Jorge',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'ORTEGA TORRES JORGE ALBERTO',
                'email' => 'ortegatorresjorgealberto9@gmail.com',
                'birth_date' => '1969-06-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 426,
                'name' => 'Dominguez',
                'paternal_lastname' => 'Sanchez',
                'maternal_lastname' => 'David',
                'full_name' => 'DOMINGUEZ SANCHEZ DAVID',
                'email' => 'david_medr@hotmail.com',
                'birth_date' => '1993-08-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 427,
                'name' => 'Gilberto',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Solis',
                'full_name' => 'HERNANDEZ SOLIS GILBERTO',
                'email' => 'gil_h_solis11@outlook.com',
                'birth_date' => '1994-04-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 428,
                'name' => 'Martinez Garcia',
                'paternal_lastname' => 'Diego',
                'maternal_lastname' => 'Djorkaef',
                'full_name' => 'MARTINEZ GARCIA DIEGO DJORKAEF',
                'email' => 'djorkaef.garcia@gmail.com',
                'birth_date' => '1966-02-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 429,
                'name' => 'Cristerna',
                'paternal_lastname' => 'Rosales',
                'maternal_lastname' => 'David',
                'full_name' => 'CRISTERNA ROSALES DAVID',
                'email' => 'mty8818@hotmail.com',
                'birth_date' => '1997-03-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 430,
                'name' => 'Gonzalez',
                'paternal_lastname' => 'Lara',
                'maternal_lastname' => 'Ventura',
                'full_name' => 'GONZALEZ LARA VENTURA',
                'email' => 'johanaesparza92@gmail.com',
                'birth_date' => '1995-04-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 431,
                'name' => 'Guardiola Herrera',
                'paternal_lastname' => 'Joseph',
                'maternal_lastname' => 'Alexis',
                'full_name' => 'GUARDIOLA HERRERA JOSEPH ALEXIS',
                'email' => 'alexxitoguarherr123@gmail.com',
                'birth_date' => '1998-05-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 432,
                'name' => 'Revolorio',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'Rolfi',
                'full_name' => 'REVOLORIO PEREZ ROLFI',
                'email' => '9621695650z@gmail.com',
                'birth_date' => '1984-10-31',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 433,
                'name' => 'Juan Daniel',
                'paternal_lastname' => 'Arellanos',
                'maternal_lastname' => 'Paulin',
                'full_name' => 'ARELLANOS PAULIN JUAN DANIEL',
                'email' => 'danielpablin123@gmail.com',
                'birth_date' => '1982-03-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 434,
                'name' => 'Castellanos Mendoza',
                'paternal_lastname' => 'Percy',
                'maternal_lastname' => 'Olivero',
                'full_name' => 'CASTELLANOS MENDOZA PERCY OLIVERO',
                'email' => 'percycastellanos43@gmail.com',
                'birth_date' => '1981-02-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 435,
                'name' => 'Hiram De Jesus',
                'paternal_lastname' => 'Rocha',
                'maternal_lastname' => 'Sarmientos',
                'full_name' => 'ROCHA SARMIENTOS HIRAM DE JESUS',
                'email' => 'hiramrochaoo@gmail.com',
                'birth_date' => '1974-08-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 436,
                'name' => 'Calderon',
                'paternal_lastname' => 'Quiroz',
                'maternal_lastname' => 'Joel',
                'full_name' => 'CALDERON QUIROZ JOEL',
                'email' => 'joel19113@gmail.com',
                'birth_date' => '1979-11-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 437,
                'name' => 'Juan Jose',
                'paternal_lastname' => 'Castillo',
                'maternal_lastname' => 'Gutierrez',
                'full_name' => 'CASTILLO GUTIERREZ JUAN JOSE',
                'email' => 'castillogutierrezjuanjose1@gmail.com',
                'birth_date' => '1984-10-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 438,
                'name' => 'Gonzalez',
                'paternal_lastname' => 'Cortes',
                'maternal_lastname' => 'Baltazar',
                'full_name' => 'GONZALEZ CORTES BALTAZAR',
                'email' => 'baltazar.gonzalez1980@hotmail.com',
                'birth_date' => '1990-09-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 439,
                'name' => 'Zapata Leija',
                'paternal_lastname' => 'Martha',
                'maternal_lastname' => 'Alicia',
                'full_name' => 'ZAPATA LEIJA MARTHA ALICIA',
                'email' => 'marthazap803@gmail.com',
                'birth_date' => '1973-02-22',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 440,
                'name' => 'Flores',
                'paternal_lastname' => 'De La Cruz',
                'maternal_lastname' => 'Zenit',
                'full_name' => 'FLORES DE LA CRUZ ZENIT',
                'email' => 'zenitflores02@outlook.com',
                'birth_date' => '1996-05-13',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 441,
                'name' => 'Sergio',
                'paternal_lastname' => 'Tolentino',
                'maternal_lastname' => 'Amador',
                'full_name' => 'TOLENTINO AMADOR SERGIO',
                'email' => 'tole.cesar93@gmail.com',
                'birth_date' => '1990-10-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 442,
                'name' => 'Claudia Paola',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Santos',
                'full_name' => 'HERNANDEZ SANTOS CLAUDIA PAOLA',
                'email' => 'psolahernandez309@gmail.com',
                'birth_date' => '1987-01-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 443,
                'name' => 'Murillo Perez',
                'paternal_lastname' => 'Jose',
                'maternal_lastname' => 'Humberto',
                'full_name' => 'MURILLO PEREZ JOSE HUMBERTO',
                'email' => 'murillo.perez.josehumberto@gmail.com',
                'birth_date' => '1997-10-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 444,
                'name' => 'Reyes Eduardo',
                'paternal_lastname' => 'Del',
                'maternal_lastname' => 'Angel',
                'full_name' => 'DEL ANGEL REYES EDUARDO',
                'email' => 'eduardodelangelreyes499@gmail.com',
                'birth_date' => '1997-03-19',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 445,
                'name' => 'Espinoza Flores',
                'paternal_lastname' => 'Rafael',
                'maternal_lastname' => 'Esau',
                'full_name' => 'ESPINOZA FLORES RAFAEL ESAU',
                'email' => 'fhannia693@gmail.com',
                'birth_date' => '2001-09-27',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 446,
                'name' => 'Placido Gerardo',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'HERNANDEZ HERNANDEZ PLACIDO GERARDO',
                'email' => 'grett.10pgh.31@gmail.com',
                'birth_date' => '1987-08-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 447,
                'name' => 'Edson Alfredo',
                'paternal_lastname' => 'Ordaz',
                'maternal_lastname' => 'Fabela',
                'full_name' => 'ORDAZ FABELA EDSON ALFREDO',
                'email' => 'edsonofficial1406@gmail.com',
                'birth_date' => '1984-02-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 448,
                'name' => 'Perez',
                'paternal_lastname' => 'Ruiz',
                'maternal_lastname' => 'Yosimar',
                'full_name' => 'PEREZ RUIZ YOSIMAR',
                'email' => 'yosimarp161@gmail.com',
                'birth_date' => '1985-07-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 449,
                'name' => 'Javier',
                'paternal_lastname' => 'Contreras',
                'maternal_lastname' => 'Carrizalez',
                'full_name' => 'CONTRERAS CARRIZALEZ JAVIER',
                'email' => 'alxcon34@gmail.com',
                'birth_date' => '1991-05-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 450,
                'name' => 'Francisco Javier',
                'paternal_lastname' => 'Bautista',
                'maternal_lastname' => 'Rivera',
                'full_name' => 'BAUTISTA RIVERA FRANCISCO JAVIER',
                'email' => 'fb812980@gmail.com',
                'birth_date' => '1982-03-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 451,
                'name' => 'Leobardo',
                'paternal_lastname' => 'Rivera',
                'maternal_lastname' => 'Gonzalez',
                'full_name' => 'RIVERA GONZALEZ LEOBARDO',
                'email' => 'rleo25670@gmail.com',
                'birth_date' => '1993-04-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 452,
                'name' => 'Andres',
                'paternal_lastname' => 'Medina',
                'maternal_lastname' => 'Denise',
                'full_name' => 'ANDRES MEDINA DENISE',
                'email' => 'denissemedina86896@gmail.com',
                'birth_date' => '1993-03-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 453,
                'name' => 'Rodriguez Gamero',
                'paternal_lastname' => 'Laura',
                'maternal_lastname' => 'Alicia',
                'full_name' => 'RODRIGUEZ GAMERO LAURA ALICIA',
                'email' => 'laura69748@gmail.com',
                'birth_date' => '1985-12-10',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 454,
                'name' => 'Morales Rodriguez',
                'paternal_lastname' => 'Darwin',
                'maternal_lastname' => 'Jael',
                'full_name' => 'MORALES RODRIGUEZ DARWIN JAEL',
                'email' => 'jaeldrawin@gmail.com',
                'birth_date' => '2002-10-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 455,
                'name' => 'Omar',
                'paternal_lastname' => 'Luna',
                'maternal_lastname' => 'Lira',
                'full_name' => 'LUNA LIRA OMAR',
                'email' => 'chino0211360@gmail.com',
                'birth_date' => '1998-06-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 456,
                'name' => 'Julio Cesar',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'Reyna',
                'full_name' => 'PEREZ REYNA JULIO CESAR',
                'email' => 'julio.cesar.perez.reyna@hotmail.com',
                'birth_date' => '1979-08-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 457,
                'name' => 'Martin Antonio',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Robles',
                'full_name' => 'HERNANDEZ ROBLES MARTIN ANTONIO',
                'email' => 'antonio-mrt29@hotmail.com',
                'birth_date' => '1990-07-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 458,
                'name' => 'Dominguez Tudon',
                'paternal_lastname' => 'Brandon',
                'maternal_lastname' => 'Isai',
                'full_name' => 'DOMINGUEZ TUDON BRANDON ISAI',
                'email' => 'brandontudon247@gmail.com',
                'birth_date' => null,
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 459,
                'name' => 'Zuñiga Vazquez',
                'paternal_lastname' => 'Leonardo',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'ZUÑIGA VAZQUEZ LEONARDO ALBERTO',
                'email' => 'leo.70199@gmail.com',
                'birth_date' => '1998-02-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 460,
                'name' => 'Gallegos Ponce',
                'paternal_lastname' => 'Karla',
                'maternal_lastname' => 'Elizabeth',
                'full_name' => 'GALLEGOS PONCE KARLA ELIZABETH',
                'email' => 'karlagallegos225@gmail.com',
                'birth_date' => '1992-03-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 461,
                'name' => 'Ramos Alvarez',
                'paternal_lastname' => 'Angelica',
                'maternal_lastname' => 'Berenice',
                'full_name' => 'RAMOS ALVAREZ ANGELICA BERENICE',
                'email' => 'ramosangelicaberenice@gmail.com',
                'birth_date' => '2002-06-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 462,
                'name' => 'Martinez Rodriguez',
                'paternal_lastname' => 'Lizbeth',
                'maternal_lastname' => 'Sarahi',
                'full_name' => 'MARTINEZ RODRIGUEZ LIZBETH SARAHI',
                'email' => 'lizbeth_sarahimtz@hotmail.com',
                'birth_date' => '1994-12-12',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 463,
                'name' => 'Jose Alfredo',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'HERNANDEZ HERNANDEZ JOSE ALFREDO',
                'email' => 'jose.015@live.com.mx',
                'birth_date' => '1983-09-08',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 464,
                'name' => 'Juan Fernando',
                'paternal_lastname' => 'Perez',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'PEREZ HERNANDEZ JUAN FERNANDO',
                'email' => 'perezhernandezjuanfernando29@gmail.com',
                'birth_date' => '1987-08-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 465,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Jahir',
                'full_name' => 'HERNANDEZ HERNANDEZ JAHIR',
                'email' => '8125867539jahir@gmail.com',
                'birth_date' => '2005-06-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 466,
                'name' => 'Armendariz Barajas',
                'paternal_lastname' => 'Mayra',
                'maternal_lastname' => 'Alejandra',
                'full_name' => 'ARMENDARIZ BARAJAS MAYRA ALEJANDRA',
                'email' => 'armendarizbarajas@gmail.com',
                'birth_date' => '1997-02-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 467,
                'name' => 'Rodriguez Vallejo',
                'paternal_lastname' => 'Axel',
                'maternal_lastname' => 'Alberto',
                'full_name' => 'RODRIGUEZ VALLEJO AXEL ALBERTO',
                'email' => 'axel125.ar43@gmail.com',
                'birth_date' => '1994-07-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 468,
                'name' => 'Roberto Carlos',
                'paternal_lastname' => 'Rodriguez',
                'maternal_lastname' => 'Campos',
                'full_name' => 'RODRIGUEZ CAMPOS ROBERTO CARLOS',
                'email' => 'rob.campos999@gmail.com',
                'birth_date' => '1982-04-15',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 469,
                'name' => 'Miguel Angel',
                'paternal_lastname' => 'Eguia',
                'maternal_lastname' => 'Medina',
                'full_name' => 'EGUIA MEDINA MIGUEL ANGEL',
                'email' => 'miguel.eguia34@gmail.com',
                'birth_date' => '1990-05-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 470,
                'name' => 'Ramos Alvarez',
                'paternal_lastname' => 'Julia',
                'maternal_lastname' => 'Isabel',
                'full_name' => 'RAMOS ALVAREZ JULIA ISABEL',
                'email' => 'julyr3520@gmail.com',
                'birth_date' => '1990-09-14',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 471,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Lucio',
                'full_name' => 'HERNANDEZ HERNANDEZ LUCIO',
                'email' => 'hernandezeskarely@gmail.com',
                'birth_date' => '1990-05-05',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 472,
                'name' => 'Jimenez',
                'paternal_lastname' => 'Fernandez',
                'maternal_lastname' => 'Esmeralda',
                'full_name' => 'JIMENEZ FERNANDEZ ESMERALDA',
                'email' => 'esmej4326@gmail.com',
                'birth_date' => '1993-01-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 473,
                'name' => 'Gadhakh Arjon',
                'paternal_lastname' => 'Lila',
                'maternal_lastname' => 'Ravina',
                'full_name' => 'GADHAKH ARJON LILA RAVINA',
                'email' => 'lila.gadakh@gmail.com',
                'birth_date' => '1997-10-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 474,
                'name' => 'Esparza Cavazos',
                'paternal_lastname' => 'Monica',
                'maternal_lastname' => 'Lizet',
                'full_name' => 'ESPARZA CAVAZOS MONICA LIZET',
                'email' => 'cavazosmony8@gmail.com',
                'birth_date' => '1995-10-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 475,
                'name' => 'Rogelio',
                'paternal_lastname' => 'Romero',
                'maternal_lastname' => 'Franco',
                'full_name' => 'ROMERO FRANCO ROGELIO',
                'email' => 'romerofrancorogelio@gmail.com',
                'birth_date' => '1983-09-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 476,
                'name' => 'Tepach',
                'paternal_lastname' => 'Cumplido',
                'maternal_lastname' => 'Perla',
                'full_name' => 'TEPACH CUMPLIDO PERLA',
                'email' => 'tepachperla2004@gmail.com',
                'birth_date' => '1966-06-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 477,
                'name' => 'Diego Jesus',
                'paternal_lastname' => 'Campos',
                'maternal_lastname' => 'Salinas',
                'full_name' => 'CAMPOS SALINAS DIEGO JESUS',
                'email' => 'diegojesush014@gmail.com',
                'birth_date' => '1990-08-06',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 478,
                'name' => 'Villanueva Lucio',
                'paternal_lastname' => 'Kevin',
                'maternal_lastname' => 'Santiago',
                'full_name' => 'VILLANUEVA LUCIO KEVIN SANTIAGO',
                'email' => 'keven3697@gmail.com',
                'birth_date' => '1980-07-25',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 479,
                'name' => 'Victor Francisco',
                'paternal_lastname' => 'Reyna',
                'maternal_lastname' => 'Rosales',
                'full_name' => 'REYNA ROSALES VICTOR FRANCISCO',
                'email' => 'sgaby3036@gmail.com',
                'birth_date' => '1991-10-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 480,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Esteban',
                'full_name' => 'HERNANDEZ HERNANDEZ ESTEBAN',
                'email' => 'hdzesteban@gmail.com',
                'birth_date' => '1982-02-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 481,
                'name' => 'Javier',
                'paternal_lastname' => 'Bautista',
                'maternal_lastname' => 'Lanche',
                'full_name' => 'BAUTISTA LANCHE JAVIER',
                'email' => 'javierbautistalanche148@gmail.com',
                'birth_date' => '1997-05-17',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 482,
                'name' => 'Santiago',
                'paternal_lastname' => 'Santiago',
                'maternal_lastname' => 'Patricio',
                'full_name' => 'SANTIAGO SANTIAGO PATRICIO',
                'email' => 'www.packosantiago@gmail.com',
                'birth_date' => '1994-01-18',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 483,
                'name' => 'Hernandez',
                'paternal_lastname' => 'Natividad',
                'maternal_lastname' => 'Faustino',
                'full_name' => 'HERNANDEZ NATIVIDAD FAUSTINO',
                'email' => 'faustino.natividad.facebook@gmail.com',
                'birth_date' => '1995-08-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 484,
                'name' => 'Torres Manzanares',
                'paternal_lastname' => 'Axel',
                'maternal_lastname' => 'Aldair',
                'full_name' => 'TORRES MANZANARES AXEL ALDAIR',
                'email' => 'jtorres52738@gmail.com',
                'birth_date' => '1974-03-16',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 485,
                'name' => 'Martinez Garcia',
                'paternal_lastname' => 'Leslie',
                'maternal_lastname' => 'Elizabeth',
                'full_name' => 'MARTINEZ GARCIA LESLIE ELIZABETH',
                'email' => 'lesliemtzg08@gmail.com',
                'birth_date' => '2000-03-01',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 486,
                'name' => 'Irving',
                'paternal_lastname' => 'Villanueva',
                'maternal_lastname' => 'Acevedo',
                'full_name' => 'VILLANUEVA ACEVEDO IRVING',
                'email' => 'irvingacevedo23@gmail.com',
                'birth_date' => '1992-10-31',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 487,
                'name' => 'Ramiro Alejandro',
                'paternal_lastname' => 'Fuentes',
                'maternal_lastname' => 'Arreola',
                'full_name' => 'FUENTES ARREOLA RAMIRO ALEJANDRO',
                'email' => 'ramirofts28@gmail.com',
                'birth_date' => '1976-08-11',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 488,
                'name' => 'Rodriguez Carreño',
                'paternal_lastname' => 'Diego',
                'maternal_lastname' => 'Aldayr',
                'full_name' => 'RODRIGUEZ CARREÑO DIEGO ALDAYR',
                'email' => 'rrodriguezdiego17@gmail.com',
                'birth_date' => '1998-07-09',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 489,
                'name' => 'Carreño Bocardo',
                'paternal_lastname' => 'Naydelin',
                'maternal_lastname' => 'Esmeralda',
                'full_name' => 'CARREÑO BOCARDO NAYDELIN ESMERALDA',
                'email' => 'esmeraldabocardo8@gmail.com',
                'birth_date' => '1983-03-03',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 490,
                'name' => 'Campos',
                'paternal_lastname' => 'Torres',
                'maternal_lastname' => 'Ever',
                'full_name' => 'CAMPOS TORRES EVER',
                'email' => '3v3rcampos@gmail.com',
                'birth_date' => '1994-03-20',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 491,
                'name' => 'Luis Gerardo',
                'paternal_lastname' => 'Saldaña De',
                'maternal_lastname' => 'Leon',
                'full_name' => 'SALDAÑA DE LEON LUIS GERARDO',
                'email' => 'leon.gera191419@gmail.com',
                'birth_date' => '1993-06-07',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 492,
                'name' => 'Cerda Silva',
                'paternal_lastname' => 'Brandon',
                'maternal_lastname' => 'Jair',
                'full_name' => 'CERDA SILVA BRANDON JAIR',
                'email' => 'brandon_54714@hotmail.com',
                'birth_date' => '1978-11-29',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 493,
                'name' => 'Ramirez',
                'paternal_lastname' => 'Hernandez',
                'maternal_lastname' => 'Ramon',
                'full_name' => 'RAMIREZ HERNANDEZ RAMON',
                'email' => 'monchyramirez016@gmail.com',
                'birth_date' => '2004-12-30',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 494,
                'name' => 'Jose Angel',
                'paternal_lastname' => 'Treviño',
                'maternal_lastname' => 'Loredo',
                'full_name' => 'TREVIÑO LOREDO JOSE ANGEL',
                'email' => 'trevinojoseangel7@gmail.com',
                'birth_date' => '1970-06-28',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 495,
                'name' => 'Garza Salcedo',
                'paternal_lastname' => 'Oscar',
                'maternal_lastname' => 'Guillermo',
                'full_name' => 'GARZA SALCEDO OSCAR GUILLERMO',
                'email' => 'oscargza31@gmail.com',
                'birth_date' => '1987-01-04',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 496,
                'name' => 'Luis Gerardo',
                'paternal_lastname' => 'Zapata',
                'maternal_lastname' => 'Rojas',
                'full_name' => 'ZAPATA ROJAS LUIS GERARDO',
                'email' => 'zapataluisgerardo5@gmail.com',
                'birth_date' => '2002-09-02',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 497,
                'name' => 'Mendoza',
                'paternal_lastname' => 'Rojas',
                'maternal_lastname' => 'Margarito',
                'full_name' => 'MENDOZA ROJAS MARGARITO',
                'email' => 'magitorojas56@gmail.com',
                'birth_date' => '1998-07-23',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 498,
                'name' => 'Rivas',
                'paternal_lastname' => 'Valadez',
                'maternal_lastname' => 'Heriberto',
                'full_name' => 'RIVAS VALADEZ HERIBERTO',
                'email' => 'heririva98@gmail.com',
                'birth_date' => '2005-08-21',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 499,
                'name' => 'Alvaro',
                'paternal_lastname' => 'Salas',
                'maternal_lastname' => 'Hernandez',
                'full_name' => 'SALAS HERNANDEZ ALVARO',
                'email' => null,
                'birth_date' => '1974-07-24',
                'password' => $password,
                'email_verified_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];
    }
}
